import LiuWang.LiuWang2025SemilinearWaveVerification

open LiuWangVerification

example :
    LiuWang2025SemilinearWaveVerification.stageStatus
        .complexGaussianStationaryPhaseCalibration = .verified :=
  LiuWang2025SemilinearWaveVerification.complexGaussianStationaryPhaseCalibration_is_verified

#check LiuWang2025SemilinearWaveComplexStationaryPhase.calibrationCertificate
#check LiuWang2025SemilinearWaveComplexStationaryPhase.chartCalibrationCertificate
#check LiuWang2025SemilinearWaveComplexStationaryPhase.composed_lead_eq_zero
#check LiuWang2025SemilinearWaveComplexStationaryPhase.chart_composed_lead_eq_zero
#check LiuWang2025SemilinearWaveComplexStationaryPhase.PaperOrderTwoStationaryPhaseInput

#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.calibrationCertificate
#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.chartCalibrationCertificate
#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.composed_lead_eq_zero
#print axioms LiuWang2025SemilinearWaveVerification.complexGaussianStationaryPhaseCalibration_is_verified
