import LiuWang.LiuWang2025SemilinearWaveGaussianBoundaryScaling

open Filter

open LiuWang2025SemilinearWaveGaussianBoundaryScaling

#check radialSquaredGaussianMoment_formula
#check sourceRadialSquaredGaussianMoment_formula
#check sourceSquaredMassExponent_collapse
#check sourceSquaredMassExponent_eq_neg_two_decayExponent
#check dimensionCorrectBoundaryDecayExponent_three
#check dimensionCorrectBoundaryDecayExponent_eq_paper_iff
#check dimensionCorrectBoundaryDecayRate_tendsto_zero
#check DimensionCorrectBoundaryDecayPacket.boundaryTrace_tendsto_zero
#check DimensionCorrectRatePointRecoveryData.coefficient_eq_zero
#check DimensionCorrectRatePointRecoveryData.certificate
#check certificate

#print axioms radialSquaredGaussianMoment_formula
#print axioms sourceSquaredMassExponent_eq_neg_two_decayExponent
#print axioms dimensionCorrectBoundaryDecayExponent_eq_paper_iff
#print axioms dimensionCorrectBoundaryDecayRate_tendsto_zero
#print axioms DimensionCorrectBoundaryDecayPacket.boundaryTrace_tendsto_zero
#print axioms DimensionCorrectRatePointRecoveryData.coefficient_eq_zero
#print axioms DimensionCorrectRatePointRecoveryData.certificate
#print axioms certificate
