import LiuWang.LiuWang2025SemilinearWaveStationaryPhaseJetCancellation

open Filter MeasureTheory Asymptotics

#check LiuWang2025SemilinearWaveComplexStationaryPhase.gaussianMoment_eq_zero_of_odd
#check LiuWang2025SemilinearWaveComplexStationaryPhase.linearGaussianCoefficient_eq_zero
#check LiuWang2025SemilinearWaveComplexStationaryPhase.cubicGaussianCoefficient_eq_zero
#check LiuWang2025SemilinearWaveComplexStationaryPhase.constantGaussianCoefficient_ne_zero
#check LiuWang2025SemilinearWaveComplexStationaryPhase.HalfPowerExpansion
#check LiuWang2025SemilinearWaveComplexStationaryPhase.HalfPowerExpansion.isBigO_beamScale_of_coefficients_eq_zero
#check LiuWang2025SemilinearWaveComplexStationaryPhase.ParityClassifiedExpansion
#check LiuWang2025SemilinearWaveComplexStationaryPhase.ParityClassifiedExpansion.isBigO_beamScale_of_secondMoment_eq_zero
#check LiuWang2025SemilinearWaveComplexStationaryPhase.NormalizedTaylorJets
#check LiuWang2025SemilinearWaveComplexStationaryPhase.NormalizedTaylorJets.firstCorrectionJet_odd
#check LiuWang2025SemilinearWaveComplexStationaryPhase.NormalizedTaylorJets.truncatedProduct_eq_secondOrderExpansion
#check LiuWang2025SemilinearWaveComplexStationaryPhase.NormalizedTaylorJets.secondCorrectionJet_even
#check LiuWang2025SemilinearWaveComplexStationaryPhase.NormalizedTaylorJets.secondGaussianCoefficient_eq_zero_iff
#check LiuWang2025SemilinearWaveComplexStationaryPhase.paperOrderTwoStationaryPhaseInput_of_parityClassifiedExpansion
#check LiuWang2025SemilinearWaveComplexStationaryPhase.ParityGeneratedExpansion
#check LiuWang2025SemilinearWaveComplexStationaryPhase.ParityGeneratedExpansion.isBigO_beamScale_of_secondCoefficient_eq_zero
#check LiuWang2025SemilinearWaveComplexStationaryPhase.paperOrderTwoStationaryPhaseInput_of_parityGeneratedExpansion

#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.linearGaussianCoefficient_eq_zero
#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.cubicGaussianCoefficient_eq_zero
#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.constantGaussianCoefficient_ne_zero
#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.NormalizedTaylorJets.firstCorrectionJet_odd
#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.NormalizedTaylorJets.truncatedProduct_eq_secondOrderExpansion
#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.NormalizedTaylorJets.secondCorrectionJet_even
#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.paperOrderTwoStationaryPhaseInput_of_parityClassifiedExpansion
#print axioms LiuWang2025SemilinearWaveComplexStationaryPhase.paperOrderTwoStationaryPhaseInput_of_parityGeneratedExpansion
