import LiuWang.LiuWang2025SemilinearWaveReflectedBeamBoundaryDecay
import Mathlib.Analysis.SpecialFunctions.Pow.Asymptotics

/-!
# Liu--Wang 2025: the Gaussian estimate on the inaccessible boundary

Source: Boya Liu and Weinan Wang, *On a partial data inverse problem for the
semi-linear wave equation*, arXiv:2511.08794v1, Sections 3.2 and 4.

After the Green identity of equation (4.3) the source is left with a single
pairing supported on the inaccessible part `partial Omega \ Gamma` of the
lateral boundary.  That pairing is discarded because the Gaussian beams used
in the argument are concentrated along null geodesics which meet the boundary
only inside `Gamma`; on the inaccessible face the beams and all of their
tangential derivatives are *exponentially* small in the large parameter
`rho`.

Until now the dossier accepted `boundary -> 0` (or a polynomial rate for it)
as an input.  This module derives it from an actual Gaussian estimate.

## Contents

* `norm_beamExponential` : the exact modulus `|e^{i rho phi}| = e^{-rho Im phi}`;
* `norm_beamExponential_le`, `norm_beamTrace_le` : the Gaussian bound when the
  imaginary part of the phase is bounded below by a positive constant, which
  is what positivity of `Im M` gives at positive distance from the beam;
* `tendsto_natPow_mul_exp_neg` : `rho^m e^{-c rho} -> 0` for every `m`;
* `InaccessibleTraceData` : the finite family of tangential derivatives of the
  boundary trace on the inaccessible face, each bounded by
  `C_alpha rho^{|alpha|} e^{-c rho}` -- one power of `rho` per derivative, the
  only loss a derivative of an oscillatory Gaussian can produce;
* `sobolevEnvelope_tendsto_zero` and `weighted_sobolevEnvelope_tendsto_zero` :
  the finite `H^k` envelope of the inaccessible trace vanishes, and vanishes
  faster than *every* polynomial rate -- in particular faster than the paper's
  displayed rate `rho^{-((N-k+1)/2 + d/4)}`, which is the near-boundary rate
  for the face the beams actually meet;
* `GaussianFarBoundaryPointRecovery` : point recovery in which the
  inaccessible-boundary limit is generated by this estimate rather than
  assumed.

## Scope

The hypothesis that the beam phase has imaginary part bounded below by a
positive constant on the inaccessible face, and that each tangential
derivative costs at most one power of `rho`, are properties of the geometric
beam construction; they are stated here as the data of
`InaccessibleTraceData`.  Everything downstream of them -- the Gaussian bound,
the finite Sobolev sum, superpolynomial decay, and the recovery endpoint -- is
proved.
-/

noncomputable section

open Filter Topology Finset
open scoped BigOperators

namespace LiuWang2025SemilinearWaveInaccessibleBoundaryDecay

/-! ## The Gaussian bound on an oscillatory factor -/

/-- Exact modulus of the beam's oscillatory factor. -/
theorem norm_beamExponential (rho : Real) (phi : Complex) :
    ‖Complex.exp (Complex.I * (rho : Complex) * phi)‖
      = Real.exp (-(rho * phi.im)) := by
  rw [Complex.norm_exp]
  congr 1
  simp [Complex.mul_re, Complex.mul_im]

/-- Positivity of the imaginary part of the phase at positive distance from
the beam gives the Gaussian bound. -/
theorem norm_beamExponential_le {rho coercivity : Real} (hrho : 0 <= rho)
    {phi : Complex} (hphi : coercivity <= phi.im) :
    ‖Complex.exp (Complex.I * (rho : Complex) * phi)‖
      <= Real.exp (-(coercivity * rho)) := by
  rw [norm_beamExponential]
  refine Real.exp_le_exp.mpr ?_
  have : coercivity * rho <= rho * phi.im := by
    rw [mul_comm coercivity rho]
    exact mul_le_mul_of_nonneg_left hphi hrho
  linarith

/-- The full beam trace on the inaccessible face is exponentially small. -/
theorem norm_beamTrace_le {rho coercivity amplitudeBound : Real}
    (hrho : 0 <= rho) {phi amplitude : Complex}
    (hphi : coercivity <= phi.im) (hamp : ‖amplitude‖ <= amplitudeBound) :
    ‖amplitude * Complex.exp (Complex.I * (rho : Complex) * phi)‖
      <= amplitudeBound * Real.exp (-(coercivity * rho)) := by
  rw [norm_mul]
  refine mul_le_mul hamp (norm_beamExponential_le hrho hphi)
    (norm_nonneg _) (le_trans (norm_nonneg amplitude) hamp)

/-! ## Superpolynomial decay -/

/-- `rho ^ m * e^{-c rho} -> 0` along the natural numbers, for every `m`. -/
theorem tendsto_natPow_mul_exp_neg (m : Nat) {coercivity : Real}
    (hc : 0 < coercivity) :
    Tendsto (fun rho : Nat => (rho : Real) ^ m * Real.exp (-(coercivity * rho)))
      atTop (nhds 0) := by
  have hreal : Tendsto
      (fun x : Real => x ^ (m : Real) * Real.exp (-coercivity * x)) atTop (nhds 0) :=
    tendsto_rpow_mul_exp_neg_mul_atTop_nhds_zero (m : Real) coercivity hc
  have hcomp := hreal.comp tendsto_natCast_atTop_atTop (α := Nat)
  refine hcomp.congr fun rho => ?_
  simp only [Function.comp_apply]
  rw [Real.rpow_natCast]
  ring_nf

/-! ## The finite tangential-derivative family on the inaccessible face -/

/-- Tangential derivatives of the beam trace on the inaccessible boundary
face.  `derivativeOrder alpha` is `|alpha|`; each derivative costs at most one
power of `rho`, and the Gaussian factor is uniform. -/
structure InaccessibleTraceData (Index E : Type*) [Fintype Index]
    [SeminormedAddCommGroup E] where
  coercivity : Real
  coercivity_pos : 0 < coercivity
  derivativeOrder : Index -> Nat
  trace : Nat -> Index -> E
  constant : Index -> Real
  constant_nonneg : ∀ alpha, 0 <= constant alpha
  norm_trace_le : ∀ (rho : Nat) (alpha : Index),
    ‖trace rho alpha‖ <=
      constant alpha *
        ((rho : Real) ^ derivativeOrder alpha * Real.exp (-(coercivity * rho)))

namespace InaccessibleTraceData

variable {Index E : Type*} [Fintype Index] [SeminormedAddCommGroup E]

/-- The finite boundary Sobolev envelope on the inaccessible face. -/
def sobolevEnvelope (D : InaccessibleTraceData Index E) (rho : Nat) : Real :=
  ∑ alpha, ‖D.trace rho alpha‖

theorem sobolevEnvelope_nonneg (D : InaccessibleTraceData Index E) (rho : Nat) :
    0 <= D.sobolevEnvelope rho :=
  Finset.sum_nonneg fun _alpha _ => norm_nonneg _

/-- Every single tangential derivative of the inaccessible trace vanishes. -/
theorem trace_tendsto_zero (D : InaccessibleTraceData Index E) (alpha : Index) :
    Tendsto (fun rho : Nat => D.trace rho alpha) atTop (nhds 0) := by
  rw [tendsto_zero_iff_norm_tendsto_zero]
  refine squeeze_zero (fun rho => norm_nonneg _)
    (fun rho => D.norm_trace_le rho alpha) ?_
  simpa using
    (tendsto_natPow_mul_exp_neg (D.derivativeOrder alpha)
      D.coercivity_pos).const_mul (D.constant alpha)

/-- **Every polynomially weighted inaccessible trace vanishes.**  The
Gaussian factor beats each fixed power of `rho`. -/
theorem weighted_trace_tendsto_zero (D : InaccessibleTraceData Index E)
    (M : Nat) (alpha : Index) :
    Tendsto (fun rho : Nat => (rho : Real) ^ M * ‖D.trace rho alpha‖)
      atTop (nhds 0) := by
  refine squeeze_zero
    (fun rho => mul_nonneg (pow_nonneg (Nat.cast_nonneg rho) M) (norm_nonneg _))
    (fun rho => ?_)
    (g := fun rho : Nat => D.constant alpha *
      ((rho : Real) ^ (M + D.derivativeOrder alpha) *
        Real.exp (-(D.coercivity * rho)))) ?_
  · have hbound := D.norm_trace_le rho alpha
    have hpow : (0 : Real) <= (rho : Real) ^ M := pow_nonneg (Nat.cast_nonneg rho) M
    calc (rho : Real) ^ M * ‖D.trace rho alpha‖
        <= (rho : Real) ^ M * (D.constant alpha *
            ((rho : Real) ^ D.derivativeOrder alpha *
              Real.exp (-(D.coercivity * rho)))) :=
          mul_le_mul_of_nonneg_left hbound hpow
      _ = D.constant alpha *
            ((rho : Real) ^ (M + D.derivativeOrder alpha) *
              Real.exp (-(D.coercivity * rho))) := by
          rw [pow_add]
          ring
  · simpa using
      (tendsto_natPow_mul_exp_neg (M + D.derivativeOrder alpha)
        D.coercivity_pos).const_mul (D.constant alpha)

/-- The whole finite boundary Sobolev envelope vanishes. -/
theorem sobolevEnvelope_tendsto_zero (D : InaccessibleTraceData Index E) :
    Tendsto D.sobolevEnvelope atTop (nhds 0) := by
  have h : Tendsto (fun rho : Nat => ∑ alpha, ‖D.trace rho alpha‖)
      atTop (nhds (∑ _alpha : Index, (0 : Real))) :=
    tendsto_finset_sum _ fun alpha _ =>
      (tendsto_zero_iff_norm_tendsto_zero.mp (D.trace_tendsto_zero alpha))
  simpa [sobolevEnvelope] using h

/-- **Superpolynomial decay of the inaccessible boundary Sobolev norm.**  For
every exponent `M`, the weighted envelope still vanishes; in particular the
inaccessible face decays faster than the paper's displayed near-boundary
rate. -/
theorem weighted_sobolevEnvelope_tendsto_zero
    (D : InaccessibleTraceData Index E) (M : Nat) :
    Tendsto (fun rho : Nat => (rho : Real) ^ M * D.sobolevEnvelope rho)
      atTop (nhds 0) := by
  have h : Tendsto
      (fun rho : Nat => ∑ alpha, (rho : Real) ^ M * ‖D.trace rho alpha‖)
      atTop (nhds (∑ _alpha : Index, (0 : Real))) :=
    tendsto_finset_sum _ fun alpha _ => D.weighted_trace_tendsto_zero M alpha
  have hrewrite : ∀ rho : Nat,
      (rho : Real) ^ M * D.sobolevEnvelope rho
        = ∑ alpha, (rho : Real) ^ M * ‖D.trace rho alpha‖ := by
    intro rho
    rw [sobolevEnvelope, Finset.mul_sum]
  simpa [hrewrite] using h

/-- Any pairing controlled by the inaccessible Sobolev envelope vanishes. -/
theorem boundaryPairing_tendsto_zero {F : Type*} [SeminormedAddCommGroup F]
    (D : InaccessibleTraceData Index E) (pairing : Nat -> F) (fluxNorm : Real)
    (hpairing : ∀ rho, ‖pairing rho‖ <= fluxNorm * D.sobolevEnvelope rho) :
    Tendsto pairing atTop (nhds 0) := by
  rw [tendsto_zero_iff_norm_tendsto_zero]
  refine squeeze_zero (fun rho => norm_nonneg _) hpairing ?_
  simpa using D.sobolevEnvelope_tendsto_zero.const_mul fluxNorm

/-- One reviewable object collecting the inaccessible-boundary estimate. -/
structure Certificate (D : InaccessibleTraceData Index E) : Prop where
  envelopeVanishes : Tendsto D.sobolevEnvelope atTop (nhds 0)
  superpolynomialDecay : ∀ M : Nat,
    Tendsto (fun rho : Nat => (rho : Real) ^ M * D.sobolevEnvelope rho)
      atTop (nhds 0)
  eachDerivativeVanishes : ∀ alpha : Index,
    Tendsto (fun rho : Nat => D.trace rho alpha) atTop (nhds 0)

/-- The certificate is generated from the Gaussian bounds. -/
def certificate (D : InaccessibleTraceData Index E) : Certificate D where
  envelopeVanishes := D.sobolevEnvelope_tendsto_zero
  superpolynomialDecay := D.weighted_sobolevEnvelope_tendsto_zero
  eachDerivativeVanishes := D.trace_tendsto_zero

end InaccessibleTraceData

/-! ## Point recovery with a generated inaccessible-boundary limit -/

open LiuWang2025SemilinearWaveGaussianRecovery

/-- Point-recovery data in which the inaccessible-boundary limit is *derived*
from the Gaussian estimate on the far face. -/
structure GaussianFarBoundaryPointRecovery (Index : Type*) [Fintype Index] where
  coefficient : Complex
  stationaryConstant : Complex
  amplitudeProduct : Complex
  principal : Nat -> Complex
  error : Nat -> Complex
  boundary : Nat -> Complex
  traceData : InaccessibleTraceData Index Complex
  fluxNorm : Real
  stationaryConstant_ne_zero : stationaryConstant ≠ 0
  amplitudeProduct_ne_zero : amplitudeProduct ≠ 0
  principal_tendsto : Tendsto principal atTop
    (nhds (stationaryConstant * coefficient * amplitudeProduct))
  error_tendsto_zero : Tendsto error atTop (nhds 0)
  boundary_le : ∀ rho, ‖boundary rho‖ <= fluxNorm * traceData.sobolevEnvelope rho
  integralIdentity : ∀ rho, principal rho + error rho = boundary rho

namespace GaussianFarBoundaryPointRecovery

variable {Index : Type*} [Fintype Index]

/-- The inaccessible-boundary limit, now a theorem. -/
theorem boundary_tendsto_zero (D : GaussianFarBoundaryPointRecovery Index) :
    Tendsto D.boundary atTop (nhds 0) :=
  D.traceData.boundaryPairing_tendsto_zero D.boundary D.fluxNorm D.boundary_le

/-- The source's point-recovery packet with its inaccessible-boundary limit
supplied by the Gaussian estimate. -/
def toPointRecoveryData (D : GaussianFarBoundaryPointRecovery Index) :
    PointRecoveryData where
  coefficient := D.coefficient
  stationaryConstant := D.stationaryConstant
  amplitudeProduct := D.amplitudeProduct
  principal := D.principal
  error := D.error
  boundary := D.boundary
  stationaryConstant_ne_zero := D.stationaryConstant_ne_zero
  amplitudeProduct_ne_zero := D.amplitudeProduct_ne_zero
  principal_tendsto := D.principal_tendsto
  error_tendsto_zero := D.error_tendsto_zero
  inaccessibleBoundary_tendsto_zero := D.boundary_tendsto_zero
  integralIdentity := D.integralIdentity

/-- Point recovery on the reachable set with the inaccessible-boundary term
discharged by the Gaussian estimate. -/
theorem coefficient_eq_zero (D : GaussianFarBoundaryPointRecovery Index) :
    D.coefficient = 0 :=
  PointRecoveryData.coefficient_eq_zero D.toPointRecoveryData

/-- One-object certificate. -/
structure Certificate (D : GaussianFarBoundaryPointRecovery Index) : Prop where
  inaccessibleBoundaryVanishes : Tendsto D.boundary atTop (nhds 0)
  coefficientZero : D.coefficient = 0

/-- Generated certificate. -/
def certificate (D : GaussianFarBoundaryPointRecovery Index) : Certificate D where
  inaccessibleBoundaryVanishes := D.boundary_tendsto_zero
  coefficientZero := D.coefficient_eq_zero

end GaussianFarBoundaryPointRecovery

end LiuWang2025SemilinearWaveInaccessibleBoundaryDecay
