import LiuWang.LiuWang2025SemilinearWaveGeneratedJetEquation
import LiuWang.LiuWang2025SemilinearWaveThirdOrderGreen

/-!
# Generated Liu--Wang third-order wave equation

This module closes the formal bridge from the factorial semilinear residual
to the third-order wave-difference data used in equations (4.2)--(4.3) of
Liu--Wang.

For a bounded `k`-linear source coefficient, Lean first proves that every
derivative below degree `k` vanishes at the zero state. It then computes the
top derivative of the factorial-normalized diagonal monomial. For a
permutation-invariant cubic coefficient, the six permutation terms cancel
the `3!` normalization exactly.

A Banach-space Faa di Bruno theorem next shows that, because the finite source
starts at cubic order and the generated solution satisfies `u(0)=0`,

`D^3 (N o u)(0)[f1,f2,f3] = A3(Du(0)f1, Du(0)f2, Du(0)f3)`.

Combining this identity with the generated higher-variation recurrence gives
the third linearized wave equation. Finally, two coefficient families with a
common linear wave operator and source insertion are converted into the
existing `ThirdOrderWaveDifferenceData` interface. Thus that interface is now
generated by the nonlinear solution maps rather than populated by separately
assumed equations.

The concrete Lorentzian graph spaces, well-posedness, Sobolev-algebra
realization of the coefficient maps, traces, and Green formula remain
paper-facing analytic inputs. This module checks the functional-calculus and
higher-linearization bridge; it does not claim a complete formalization of the
paper.
-/

noncomputable section

open scoped BigOperators Topology

namespace LiuWang2025SemilinearWaveGeneratedThirdOrder

open LiuWang2025SemilinearWaveFactorialImplicitSolutionMap
open LiuWang2025SemilinearWaveFactorialImplicitSolutionMap.Data
open LiuWang2025SemilinearWaveSolutionMapFaaDiBruno
open LiuWang2025SemilinearWaveThirdOrderGreen

variable {State Residual : Type*}
variable [NormedAddCommGroup State] [NormedSpace Complex State]
variable [CompleteSpace State]
variable [NormedAddCommGroup Residual] [NormedSpace Complex Residual]
variable [CompleteSpace Residual]

/-! ## Derivatives of factorial-normalized multilinear monomials -/

/-- Every derivative below the degree of a bounded multilinear diagonal
monomial vanishes at the zero state. -/
theorem diagonalMonomial_iteratedFDeriv_zero_of_lt
    {k r : Nat} (hr : r < k)
    (coefficient : State [×k]→L[Complex] Residual) :
    iteratedFDeriv Complex r (diagonalMonomial k coefficient) 0 = 0 := by
  unfold diagonalMonomial
  change iteratedFDeriv Complex r
      (coefficient ∘ (diagonalMap (State := State) k)) 0 = 0
  rw [ContinuousLinearMap.iteratedFDeriv_comp_right
    (diagonalMap (State := State) k) coefficient.contDiff (0 : State) le_rfl]
  have hcoefficient :
      iteratedFDeriv Complex r coefficient
        (diagonalMap (State := State) k 0) = 0 := by
    apply norm_eq_zero.mp
    apply le_antisymm
    · refine (coefficient.norm_iteratedFDeriv_le r
        (diagonalMap (State := State) k 0)).trans ?_
      have hne : k - r ≠ 0 := Nat.ne_of_gt (Nat.sub_pos_of_lt hr)
      rw [Fintype.card_fin, map_zero, norm_zero, zero_pow hne]
      simp
    · exact norm_nonneg _
  rw [hcoefficient]
  rfl

/-- Factorial normalization does not alter the vanishing of derivatives
strictly below the homogeneous degree. -/
theorem normalizedFactorialTerm_iteratedFDeriv_zero_of_lt
    {k r : Nat} (hr : r < k)
    (coefficient : State [×k]→L[Complex] Residual) :
    iteratedFDeriv Complex r (normalizedFactorialTerm k coefficient) 0 = 0 := by
  unfold normalizedFactorialTerm
  rw [iteratedFDeriv_const_smul_apply'
    (diagonalMonomial_contDiff k coefficient r).contDiffAt]
  rw [diagonalMonomial_iteratedFDeriv_zero_of_lt hr coefficient]
  simp

/-- Exact top derivative of a factorial-normalized diagonal monomial. The
result is the average over all permutations of the coefficient slots. -/
theorem iteratedFDeriv_normalizedFactorialTerm
    (k : Nat) (coefficient : State [×k]→L[Complex] Residual)
    (direction : Fin k -> State) :
    iteratedFDeriv Complex k (normalizedFactorialTerm k coefficient)
        0 direction =
      (Nat.factorial k : Complex)⁻¹ •
        ∑ sigma : Equiv.Perm (Fin k),
          coefficient (fun i => direction (sigma i)) := by
  unfold normalizedFactorialTerm
  rw [iteratedFDeriv_const_smul_apply'
    (diagonalMonomial_contDiff k coefficient k).contDiffAt]
  simp only [ContinuousMultilinearMap.smul_apply]
  congr 1
  exact ContinuousMultilinearMap.iteratedFDeriv_comp_diagonal
    coefficient 0 direction

/-- The symmetry condition satisfied by pointwise Nemytskii products and by
any symmetric multilinear Taylor coefficient. -/
def IsPermutationInvariant (k : Nat)
    (coefficient : State [×k]→L[Complex] Residual) : Prop :=
  forall sigma : Equiv.Perm (Fin k), forall direction : Fin k -> State,
    coefficient (fun i => direction (sigma i)) = coefficient direction

/-- For a symmetric coefficient, factorial normalization makes the top
derivative equal to the coefficient itself. -/
theorem iteratedFDeriv_normalizedFactorialTerm_of_permutationInvariant
    (k : Nat) (coefficient : State [×k]→L[Complex] Residual)
    (hsymmetric : IsPermutationInvariant k coefficient)
    (direction : Fin k -> State) :
    iteratedFDeriv Complex k (normalizedFactorialTerm k coefficient)
        0 direction = coefficient direction := by
  rw [iteratedFDeriv_normalizedFactorialTerm k coefficient direction]
  have hsum :
      (∑ sigma : Equiv.Perm (Fin k),
          coefficient (fun i => direction (sigma i))) =
        (Nat.factorial k : Complex) • coefficient direction := by
    rw [Finset.sum_congr rfl (fun sigma _ => hsymmetric sigma direction)]
    rw [Finset.sum_const, Finset.card_univ, Fintype.card_perm,
      Fintype.card_fin]
    exact (Nat.cast_smul_eq_nsmul Complex (Nat.factorial k)
      (coefficient direction)).symm
  rw [hsum, smul_smul]
  rw [inv_mul_cancel₀]
  · simp
  · exact_mod_cast Nat.factorial_ne_zero k

/-! ## The cubic derivative of the finite factorial source -/

variable {Parameter : Type*}
variable [NormedAddCommGroup Parameter] [NormedSpace Complex Parameter]
variable [CompleteSpace Parameter]

/-- Since every source degree is at least three, all source derivatives of
orders zero, one, and two vanish at the zero state. -/
theorem nonlinearResidual_iteratedFDeriv_eq_zero_of_lt_three
    {order r : Nat} (hr : r < 3)
    (data : LiuWang2025SemilinearWaveFactorialImplicitSolutionMap.Data
      (Parameter := Parameter) (State := State) (Residual := Residual) order) :
    iteratedFDeriv Complex r data.nonlinearResidual 0 = 0 := by
  unfold nonlinearResidual
  rw [iteratedFDeriv_fun_sum_apply]
  · apply Finset.sum_eq_zero
    intro k hk
    have hk3 : 3 <= k := (Finset.mem_Icc.mp hk).1
    exact normalizedFactorialTerm_iteratedFDeriv_zero_of_lt
      (lt_of_lt_of_le hr hk3) (data.sourceCoefficient k)
  · intro k hk
    exact (normalizedFactorialTerm_contDiff k
      (data.sourceCoefficient k) r).contDiffAt

/-- The third derivative of the complete finite factorial source extracts
exactly its symmetric cubic coefficient; every degree above three vanishes. -/
theorem nonlinearResidual_thirdDerivative
    {order : Nat} (horder : 3 <= order)
    (data : LiuWang2025SemilinearWaveFactorialImplicitSolutionMap.Data
      (Parameter := Parameter) (State := State) (Residual := Residual) order)
    (hsymmetric : IsPermutationInvariant 3 (data.sourceCoefficient 3))
    (direction : Fin 3 -> State) :
    iteratedFDeriv Complex 3 data.nonlinearResidual 0 direction =
      data.sourceCoefficient 3 direction := by
  unfold nonlinearResidual
  rw [iteratedFDeriv_fun_sum_apply]
  · rw [ContinuousMultilinearMap.sum_apply]
    rw [Finset.sum_eq_single 3]
    · exact iteratedFDeriv_normalizedFactorialTerm_of_permutationInvariant
        3 (data.sourceCoefficient 3) hsymmetric direction
    · intro k hk hkne
      have hk3 : 3 <= k := (Finset.mem_Icc.mp hk).1
      have h3k : 3 < k := lt_of_le_of_ne hk3 (Ne.symm hkne)
      rw [normalizedFactorialTerm_iteratedFDeriv_zero_of_lt
        h3k (data.sourceCoefficient k)]
      rfl
    · intro hnot
      exact (hnot (by simpa using horder : 3 ∈ Finset.Icc 3 order)).elim
  · intro k hk
    exact (normalizedFactorialTerm_contDiff k
      (data.sourceCoefficient k) 3).contDiffAt

/-! ## Faa di Bruno collapse at a zero background -/

/-- One Banach-valued composition term indexed by an ordered partition. -/
def compositionPartitionTerm {n : Nat}
    (source : State -> Residual) (solution : Parameter -> State)
    (base : Parameter) (partition : OrderedFinpartition n) :
    Parameter [×n]→L[Complex] Residual :=
  (ftaylorSeries Complex source (solution base)).compAlongOrderedFinpartition
    (ftaylorSeries Complex solution base) partition

/-- Full finite Faa di Bruno expansion for a Banach-valued composition. -/
theorem iteratedFDeriv_comp_eq_partitionSum
    {n : Nat} (source : State -> Residual)
    (solution : Parameter -> State) (base : Parameter)
    (hsource : ContDiffAt Complex n source (solution base))
    (hsolution : ContDiffAt Complex n solution base) :
    iteratedFDeriv Complex n (source ∘ solution) base =
      ∑ partition : OrderedFinpartition n,
        compositionPartitionTerm source solution base partition := by
  rw [iteratedFDeriv_comp hsource hsolution le_rfl]
  rfl

/-- The atomic singleton partition contains the top outer derivative applied
only to first solution derivatives. -/
theorem atomicCompositionPartitionTerm
    {n : Nat} (source : State -> Residual)
    (solution : Parameter -> State) (base : Parameter)
    (hbase : solution base = 0) (direction : Fin n -> Parameter) :
    compositionPartitionTerm source solution base
        (OrderedFinpartition.atomic n) direction =
      iteratedFDeriv Complex n source 0
        (fun i => iteratedFDeriv Complex 1 solution base
          (fun _ => direction i)) := by
  unfold compositionPartitionTerm ftaylorSeries
  simp only [FormalMultilinearSeries.compAlongOrderedFinpartition_apply,
    OrderedFinpartition.atomic_length,
    OrderedFinpartition.applyOrderedFinpartition_apply,
    OrderedFinpartition.atomic_partSize,
    OrderedFinpartition.atomic_emb]
  rw [hbase]
  rfl

/-- If every lower outer derivative vanishes, every non-atomic composition
partition vanishes. -/
theorem nonAtomicCompositionPartitionTerm_eq_zero
    {n : Nat} (source : State -> Residual)
    (solution : Parameter -> State) (base : Parameter)
    (hsourceLower : forall r, r < n ->
      iteratedFDeriv Complex r source (solution base) = 0)
    (partition : OrderedFinpartition n)
    (hne : partition ≠ OrderedFinpartition.atomic n) :
    compositionPartitionTerm source solution base partition = 0 := by
  have hlength := orderedFinpartition_length_lt_of_ne_atomic partition hne
  unfold compositionPartitionTerm ftaylorSeries
  unfold FormalMultilinearSeries.compAlongOrderedFinpartition
  change partition.compAlongOrderedFinpartition
      (iteratedFDeriv Complex partition.length source (solution base))
      (fun block => iteratedFDeriv Complex (partition.partSize block)
        solution base) = 0
  rw [hsourceLower partition.length hlength]
  apply ContinuousMultilinearMap.ext
  intro direction
  simp [OrderedFinpartition.compAlongOrderFinpartition_apply]

/-- When the solution background is zero and all lower source derivatives
vanish, Faa di Bruno collapses to its atomic singleton partition. -/
theorem iteratedFDeriv_comp_eq_atomic_of_lower_outer_zero
    {n : Nat} (source : State -> Residual)
    (solution : Parameter -> State) (base : Parameter)
    (hsource : ContDiffAt Complex n source 0)
    (hsolution : ContDiffAt Complex n solution base)
    (hbase : solution base = 0)
    (hsourceLower : forall r, r < n ->
      iteratedFDeriv Complex r source 0 = 0)
    (direction : Fin n -> Parameter) :
    iteratedFDeriv Complex n (source ∘ solution) base direction =
      iteratedFDeriv Complex n source 0
        (fun i => iteratedFDeriv Complex 1 solution base
          (fun _ => direction i)) := by
  have hsourceAt : ContDiffAt Complex n source (solution base) := by
    simpa [hbase] using hsource
  rw [iteratedFDeriv_comp_eq_partitionSum source solution base
    hsourceAt hsolution]
  rw [ContinuousMultilinearMap.sum_apply]
  rw [Finset.sum_eq_single (OrderedFinpartition.atomic n)]
  · exact atomicCompositionPartitionTerm source solution base hbase direction
  · intro partition hpartition hne
    rw [nonAtomicCompositionPartitionTerm_eq_zero source solution base
      (fun r hr => by rw [hbase]; exact hsourceLower r hr) partition hne]
    rfl
  · intro hnot
    exact (hnot (Finset.mem_univ _)).elim

/-! ## Generated third-order source and wave equation -/

/-- The third derivative of the nonlinear source along the generated
solution map is the cubic coefficient applied to the three generated first
variations. -/
theorem generatedThirdNonlinearSource_eq_cubicCoefficient
    {order : Nat} (horder : 3 <= order)
    (data : LiuWang2025SemilinearWaveFactorialImplicitSolutionMap.Data
      (Parameter := Parameter) (State := State) (Residual := Residual) order)
    (hsymmetric : IsPermutationInvariant 3 (data.sourceCoefficient 3))
    (direction : Fin 3 -> Parameter) :
    iteratedFDeriv Complex 3
        (data.nonlinearResidual ∘ data.solutionMap (by omega)) 0 direction =
      data.sourceCoefficient 3
        (fun i => fderiv Complex (data.solutionMap (by omega)) 0 (direction i)) := by
  rw [iteratedFDeriv_comp_eq_atomic_of_lower_outer_zero
    data.nonlinearResidual (data.solutionMap (by omega)) 0
    ((data.nonlinearResidual_contDiff.contDiffAt).of_le
      (by exact_mod_cast horder))
    ((data.solutionMap_contDiffAt (by omega)).of_le
      (by exact_mod_cast horder))
    (data.solutionMap_zero (by omega))
    (fun r hr => nonlinearResidual_iteratedFDeriv_eq_zero_of_lt_three hr data)
    direction]
  rw [nonlinearResidual_thirdDerivative horder data hsymmetric]
  congr 1
  funext i
  simp [iteratedFDeriv_one_apply]

/-- Generated equation (4.2): the third solution variation solves the linear
wave equation with the cubic source built from the three first variations. -/
theorem generatedThirdVariation_equation
    {order : Nat} (horder : 3 <= order)
    (data : LiuWang2025SemilinearWaveFactorialImplicitSolutionMap.Data
      (Parameter := Parameter) (State := State) (Residual := Residual) order)
    (hsymmetric : IsPermutationInvariant 3 (data.sourceCoefficient 3))
    (direction : Fin 3 -> Parameter) :
    data.linearResidual
        (iteratedFDeriv Complex 3 (data.solutionMap (by omega)) 0 direction) =
      -data.sourceCoefficient 3
        (fun i => fderiv Complex (data.solutionMap (by omega)) 0 (direction i)) := by
  rw [show data.linearResidual
          (iteratedFDeriv Complex 3 (data.solutionMap (by omega)) 0 direction) =
        -iteratedFDeriv Complex 3
          (data.nonlinearResidual ∘ data.solutionMap (by omega)) 0 direction by
    exact LiuWang2025SemilinearWaveGeneratedJetEquation.Data.higherVariation_equation
      data (by omega) (by omega) horder direction]
  rw [generatedThirdNonlinearSource_eq_cubicCoefficient horder data hsymmetric]

/-! ## Cubic coefficient adapter -/

/-- Continuous linear identification of one-variable multilinear maps with
continuous linear maps. -/
def curryFinOneMap :
    (State [×1]→L[Complex] Residual) →L[Complex]
      State →L[Complex] Residual :=
  (continuousMultilinearCurryFin1 Complex State Residual).toContinuousLinearEquiv
    |>.toContinuousLinearMap

/-- Continuous linear currying of a bounded bilinear coefficient. -/
def curryQuadraticMap :
    (State [×2]→L[Complex] Residual) →L[Complex]
      State →L[Complex] State →L[Complex] Residual :=
  (ContinuousLinearMap.compL Complex State
      (State [×1]→L[Complex] Residual) (State →L[Complex] Residual)
      (curryFinOneMap (State := State) (Residual := Residual))).comp
    (continuousMultilinearCurryLeftEquiv Complex
      (fun _ : Fin 2 => State) Residual).toContinuousLinearEquiv.toContinuousLinearMap

/-- Curried form of a bounded trilinear coefficient. -/
def curryCubicCoefficient
    (coefficient : State [×3]→L[Complex] Residual) :
    State →L[Complex] State →L[Complex] State →L[Complex] Residual :=
  (curryQuadraticMap (State := State) (Residual := Residual)).comp
    coefficient.curryLeft

@[simp] theorem curryCubicCoefficient_apply
    (coefficient : State [×3]→L[Complex] Residual) (w1 w2 w3 : State) :
    curryCubicCoefficient coefficient w1 w2 w3 = coefficient ![w1, w2, w3] := by
  simp [curryCubicCoefficient, curryQuadraticMap, curryFinOneMap]

theorem curryCubicCoefficient_family
    (coefficient : State [×3]→L[Complex] Residual) (w : Fin 3 -> State) :
    curryCubicCoefficient coefficient (w 0) (w 1) (w 2) = coefficient w := by
  rw [curryCubicCoefficient_apply]
  congr 1
  funext i
  fin_cases i <;> rfl

/-- The coefficient carrier used by the abstract Green-identity interface. -/
abbrev CurriedCubicCoefficient :=
  State →L[Complex] State →L[Complex] State →L[Complex] Residual

/-- Evaluation of a continuous curried cubic coefficient as the algebraic
four-linear `CubicSourceMap` expected by `ThirdOrderWaveDifferenceData`. -/
def continuousCubicSourceMap :
    CubicSourceMap
      (Coefficient := CurriedCubicCoefficient
        (State := State) (Residual := Residual))
      (FirstVariation := State) (Residual := Residual) where
  toFun coefficient :=
    { toFun := fun w1 =>
        { toFun := fun w2 => (coefficient w1 w2).toLinearMap
          map_add' := by
            intro x y
            ext w3
            simp
          map_smul' := by
            intro c x
            ext w3
            simp }
      map_add' := by
        intro x y
        ext w2 w3
        simp
      map_smul' := by
        intro c x
        ext w2 w3
        simp }
  map_add' := by
    intro x y
    ext w1 w2 w3
    simp
  map_smul' := by
    intro c x
    ext w1 w2 w3
    simp

@[simp] theorem continuousCubicSourceMap_apply
    (coefficient : CurriedCubicCoefficient
      (State := State) (Residual := Residual)) (w1 w2 w3 : State) :
    continuousCubicSourceMap (State := State) (Residual := Residual)
      coefficient w1 w2 w3 = coefficient w1 w2 w3 :=
  rfl

/-! ## Two generated solution maps and the Green-identity interface -/

variable {Probe BoundaryFlux BoundaryValue : Type*}
variable [AddCommGroup Probe] [Module Complex Probe]
variable [AddCommGroup BoundaryFlux] [Module Complex BoundaryFlux]
variable [AddCommGroup BoundaryValue] [Module Complex BoundaryValue]

/-- Two factorial coefficient families sharing the same linear wave operator
and source insertion. The wave field identifies that common operator with the
operator in the Green-identity engine. -/
structure GeneratedCubicComparisonData
    (G : WaveGreenIdentityEngine
      (State := State) (Residual := Residual) (Probe := Probe)
      (BoundaryFlux := BoundaryFlux) (BoundaryValue := BoundaryValue))
    (order : Nat) where
  linearResidual : State ≃L[Complex] Residual
  parameterInsertion : Parameter →L[Complex] Residual
  sourceCoefficient1 : (k : Nat) -> State [×k]→L[Complex] Residual
  sourceCoefficient2 : (k : Nat) -> State [×k]→L[Complex] Residual
  cubicCoefficient1_permutationInvariant :
    IsPermutationInvariant 3 (sourceCoefficient1 3)
  cubicCoefficient2_permutationInvariant :
    IsPermutationInvariant 3 (sourceCoefficient2 3)
  wave_eq_linearResidual : G.wave = linearResidual.toLinearMap

namespace GeneratedCubicComparisonData

variable
  {G : WaveGreenIdentityEngine
    (State := State) (Residual := Residual) (Probe := Probe)
    (BoundaryFlux := BoundaryFlux) (BoundaryValue := BoundaryValue)}
  {order : Nat}

/-- First finite factorial residual model. -/
def factorialData1 (comparison : GeneratedCubicComparisonData
    (Parameter := Parameter) G order) :
    LiuWang2025SemilinearWaveFactorialImplicitSolutionMap.Data
      (Parameter := Parameter) (State := State) (Residual := Residual) order where
  linearResidual := comparison.linearResidual
  parameterInsertion := comparison.parameterInsertion
  sourceCoefficient := comparison.sourceCoefficient1

/-- Second finite factorial residual model. -/
def factorialData2 (comparison : GeneratedCubicComparisonData
    (Parameter := Parameter) G order) :
    LiuWang2025SemilinearWaveFactorialImplicitSolutionMap.Data
      (Parameter := Parameter) (State := State) (Residual := Residual) order where
  linearResidual := comparison.linearResidual
  parameterInsertion := comparison.parameterInsertion
  sourceCoefficient := comparison.sourceCoefficient2

/-- Common first linearized wave generated by the shared linear residual and
source insertion. -/
def firstVariation (comparison : GeneratedCubicComparisonData
    (Parameter := Parameter) G order) (direction : Parameter) : State :=
  comparison.linearResidual.symm (comparison.parameterInsertion direction)

theorem fderiv_factorialData1_solutionMap
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter) G order)
    (horder : 1 <= order) (direction : Parameter) :
    fderiv Complex (comparison.factorialData1.solutionMap horder) 0 direction =
      comparison.firstVariation direction := by
  rw [comparison.factorialData1.fderiv_solutionMap_zero]
  rfl

theorem fderiv_factorialData2_solutionMap
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter) G order)
    (horder : 1 <= order) (direction : Parameter) :
    fderiv Complex (comparison.factorialData2.solutionMap horder) 0 direction =
      comparison.firstVariation direction := by
  rw [comparison.factorialData2.fderiv_solutionMap_zero]
  rfl

/-- Third derivative of the first generated solution map. -/
def thirdVariation1
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter) G order)
    (horder : 3 <= order) (direction : Fin 3 -> Parameter) : State :=
  iteratedFDeriv Complex 3
    (comparison.factorialData1.solutionMap (by omega)) 0 direction

/-- Third derivative of the second generated solution map. -/
def thirdVariation2
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter) G order)
    (horder : 3 <= order) (direction : Fin 3 -> Parameter) : State :=
  iteratedFDeriv Complex 3
    (comparison.factorialData2.solutionMap (by omega)) 0 direction

/-- First generated equation (4.2). -/
theorem generatedEquation1
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter) G order)
    (horder : 3 <= order) (direction : Fin 3 -> Parameter) :
    G.wave (comparison.thirdVariation1 horder direction) =
      -continuousCubicSourceMap (State := State) (Residual := Residual)
        (curryCubicCoefficient (State := State) (Residual := Residual)
          (comparison.sourceCoefficient1 3))
        (comparison.firstVariation (direction 0))
        (comparison.firstVariation (direction 1))
        (comparison.firstVariation (direction 2)) := by
  rw [comparison.wave_eq_linearResidual]
  change comparison.linearResidual
      (iteratedFDeriv Complex 3
        (comparison.factorialData1.solutionMap (by omega)) 0 direction) = _
  have hequation := generatedThirdVariation_equation horder
    comparison.factorialData1
    comparison.cubicCoefficient1_permutationInvariant direction
  change comparison.linearResidual
      (iteratedFDeriv Complex 3
        (comparison.factorialData1.solutionMap (by omega)) 0 direction) =
      -comparison.sourceCoefficient1 3
        (fun i => fderiv Complex
          (comparison.factorialData1.solutionMap (by omega)) 0 (direction i)) at hequation
  rw [hequation]
  congr 1
  rw [continuousCubicSourceMap_apply]
  rw [curryCubicCoefficient_apply]
  congr 1
  funext i
  fin_cases i <;>
    rw [comparison.fderiv_factorialData1_solutionMap (by omega)] <;> rfl

/-- Second generated equation (4.2). -/
theorem generatedEquation2
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter) G order)
    (horder : 3 <= order) (direction : Fin 3 -> Parameter) :
    G.wave (comparison.thirdVariation2 horder direction) =
      -continuousCubicSourceMap (State := State) (Residual := Residual)
        (curryCubicCoefficient (State := State) (Residual := Residual)
          (comparison.sourceCoefficient2 3))
        (comparison.firstVariation (direction 0))
        (comparison.firstVariation (direction 1))
        (comparison.firstVariation (direction 2)) := by
  rw [comparison.wave_eq_linearResidual]
  change comparison.linearResidual
      (iteratedFDeriv Complex 3
        (comparison.factorialData2.solutionMap (by omega)) 0 direction) = _
  have hequation := generatedThirdVariation_equation horder
    comparison.factorialData2
    comparison.cubicCoefficient2_permutationInvariant direction
  change comparison.linearResidual
      (iteratedFDeriv Complex 3
        (comparison.factorialData2.solutionMap (by omega)) 0 direction) =
      -comparison.sourceCoefficient2 3
        (fun i => fderiv Complex
          (comparison.factorialData2.solutionMap (by omega)) 0 (direction i)) at hequation
  rw [hequation]
  congr 1
  rw [continuousCubicSourceMap_apply]
  rw [curryCubicCoefficient_apply]
  congr 1
  funext i
  fin_cases i <;>
    rw [comparison.fderiv_factorialData2_solutionMap (by omega)] <;> rfl

/-- Paper-shaped third-order comparison data generated from the two nonlinear
implicit solution maps. -/
def toThirdOrderWaveDifferenceData
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter) G order)
    (horder : 3 <= order) (direction : Fin 3 -> Parameter) :
    ThirdOrderWaveDifferenceData G
      (Coefficient := CurriedCubicCoefficient
        (State := State) (Residual := Residual))
      (FirstVariation := State) where
  cubicSource := continuousCubicSourceMap (State := State) (Residual := Residual)
  coefficient1 := curryCubicCoefficient (State := State) (Residual := Residual)
    (comparison.sourceCoefficient1 3)
  coefficient2 := curryCubicCoefficient (State := State) (Residual := Residual)
    (comparison.sourceCoefficient2 3)
  w1 := comparison.firstVariation (direction 0)
  w2 := comparison.firstVariation (direction 1)
  w3 := comparison.firstVariation (direction 2)
  thirdVariation1 := comparison.thirdVariation1 horder direction
  thirdVariation2 := comparison.thirdVariation2 horder direction
  equation1 := comparison.generatedEquation1 horder direction
  equation2 := comparison.generatedEquation2 horder direction

/-- Certificate that the individual third-order equations and their
coefficient-difference equation all come from the generated solution maps. -/
structure Certificate
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter) G order)
    (horder : 3 <= order) (direction : Fin 3 -> Parameter) : Prop where
  firstSolutionMapEquation :
    G.wave
        (comparison.toThirdOrderWaveDifferenceData horder direction).thirdVariation1 =
      -(comparison.toThirdOrderWaveDifferenceData horder direction).cubicSource
        (comparison.toThirdOrderWaveDifferenceData horder direction).coefficient1
        (comparison.toThirdOrderWaveDifferenceData horder direction).w1
        (comparison.toThirdOrderWaveDifferenceData horder direction).w2
        (comparison.toThirdOrderWaveDifferenceData horder direction).w3
  secondSolutionMapEquation :
    G.wave
        (comparison.toThirdOrderWaveDifferenceData horder direction).thirdVariation2 =
      -(comparison.toThirdOrderWaveDifferenceData horder direction).cubicSource
        (comparison.toThirdOrderWaveDifferenceData horder direction).coefficient2
        (comparison.toThirdOrderWaveDifferenceData horder direction).w1
        (comparison.toThirdOrderWaveDifferenceData horder direction).w2
        (comparison.toThirdOrderWaveDifferenceData horder direction).w3
  generatedDifferenceEquation :
    G.wave
        (comparison.toThirdOrderWaveDifferenceData horder direction).variationDifference =
      -(comparison.toThirdOrderWaveDifferenceData horder direction).coefficientDifferenceSource

/-- Canonical certificate for the generated third-order comparison route. -/
def certificate
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter) G order)
    (horder : 3 <= order) (direction : Fin 3 -> Parameter) :
    Certificate comparison horder direction where
  firstSolutionMapEquation :=
    (comparison.toThirdOrderWaveDifferenceData horder direction).equation1
  secondSolutionMapEquation :=
    (comparison.toThirdOrderWaveDifferenceData horder direction).equation2
  generatedDifferenceEquation :=
    (comparison.toThirdOrderWaveDifferenceData horder direction).wave_variationDifference

end GeneratedCubicComparisonData

end LiuWang2025SemilinearWaveGeneratedThirdOrder
