import LiuWang.LiuWang2025SemilinearWaveComplexStationaryPhaseCalibration

/-!
# Liu--Wang stationary-phase jet cancellation

This module isolates the finite asymptotic algebra needed to improve the
generic complex stationary-phase estimate toward the `rho^(-2)` remainder in
equation (4.4).

The complex Gaussian is even. Consequently, every odd linear or cubic jet has
zero Gaussian moment. This removes the `rho^(-1/2)` and `rho^(-3/2)`
coefficients once a source-specific half-power expansion identifies them with
those moments. The even `rho^(-1)` coefficient is different: a constant even
jet has the nonzero Gaussian leading moment. Its cancellation therefore
remains a genuine paper-specific amplitude/phase condition.

The final bridge accepts a finite half-power expansion with an
`O(rho^(-2))` tail and proves the paper-order estimate from odd-jet parity plus
vanishing of the second coefficient. It does not assert that the Liu--Wang
beam amplitudes already provide that expansion or the even cancellation.
-/

noncomputable section

open Filter MeasureTheory Asymptotics
open scoped Real Topology

namespace LiuWang2025SemilinearWaveComplexStationaryPhase

section GaussianMoments

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace Real V]
  [FiniteDimensional Real V] [MeasurableSpace V] [BorelSpace V]

/-- Gaussian moment of a jet against the complex quadratic normal form. -/
def gaussianMoment (mu : Measure V) (H : V →L[Real] V →L[Real] Complex)
    (jet : V -> Complex) : Complex :=
  ∫ u, jet u * gaussKernel H u ∂mu

/-- Every odd jet has zero moment against the even complex Gaussian. -/
theorem gaussianMoment_eq_zero_of_odd
    (mu : Measure V) [mu.IsAddHaarMeasure]
    (H : V →L[Real] V →L[Real] Complex) (jet : V -> Complex)
    (hodd : forall u, jet (-u) = -jet u) :
    gaussianMoment mu H jet = 0 := by
  unfold gaussianMoment
  apply integral_eq_zero_of_odd mu
  intro u
  simp only [gaussKernel_neg, hodd, neg_mul]

/-- First correction coefficient generated by a linear amplitude jet. -/
def linearGaussianCoefficient (mu : Measure V)
    (H : V →L[Real] V →L[Real] Complex) (ell : V →L[Real] Complex) : Complex :=
  gaussianMoment mu H ell

/-- Linear Gaussian corrections vanish by parity. -/
theorem linearGaussianCoefficient_eq_zero
    (mu : Measure V) [mu.IsAddHaarMeasure]
    (H : V →L[Real] V →L[Real] Complex) (ell : V →L[Real] Complex) :
    linearGaussianCoefficient mu H ell = 0 := by
  apply gaussianMoment_eq_zero_of_odd mu H ell
  intro u
  exact map_neg ell u

/-- Third correction coefficient generated by a trilinear amplitude/phase jet. -/
def cubicGaussianCoefficient (mu : Measure V)
    (H : V →L[Real] V →L[Real] Complex)
    (cubic : V →L[Real] V →L[Real] V →L[Real] Complex) : Complex :=
  gaussianMoment mu H (fun u => cubic u u u)

/-- Cubic Gaussian corrections vanish by parity. -/
theorem cubicGaussianCoefficient_eq_zero
    (mu : Measure V) [mu.IsAddHaarMeasure]
    (H : V →L[Real] V →L[Real] Complex)
    (cubic : V →L[Real] V →L[Real] V →L[Real] Complex) :
    cubicGaussianCoefficient mu H cubic = 0 := by
  apply gaussianMoment_eq_zero_of_odd mu H (fun u => cubic u u u)
  intro u
  simp

/-- The constant even jet produces the leading Gaussian moment. -/
def constantGaussianCoefficient (mu : Measure V)
    (H : V →L[Real] V →L[Real] Complex) : Complex :=
  gaussianMoment mu H (fun _ => 1)

omit [FiniteDimensional Real V] [BorelSpace V] in
theorem constantGaussianCoefficient_eq_gaussConst
    (mu : Measure V) (H : V →L[Real] V →L[Real] Complex) :
    constantGaussianCoefficient mu H = gaussConst mu H := by
  simp [constantGaussianCoefficient, gaussianMoment, gaussConst]

/-- Even coefficients do not vanish from Gaussian parity alone. -/
theorem constantGaussianCoefficient_ne_zero
    (mu : Measure V) [mu.IsAddHaarMeasure] (P : PhaseData V) :
    constantGaussianCoefficient mu P.H ≠ 0 := by
  rw [constantGaussianCoefficient_eq_gaussConst]
  exact gaussConst_phase_ne_zero mu P

end GaussianMoments

/-! ## Finite half-power expansion -/

/-- The `degree`th half-power scale `(sqrt rho)^(-degree)`. -/
def halfPowerScale (degree : Nat) (rho : Real) : Complex :=
  (((Real.sqrt rho)⁻¹ ^ degree : Real) : Complex)

/-- The three corrections lying strictly above the `rho^(-2)` scale. -/
def firstThreeCorrections (c1 c2 c3 : Complex) (rho : Real) : Complex :=
  halfPowerScale 1 rho * c1 +
    halfPowerScale 2 rho * c2 +
    halfPowerScale 3 rho * c3

/-- A finite stationary-phase expansion through order `rho^(-3/2)`, with
the unresolved tail already controlled at `rho^(-2)`. -/
structure HalfPowerExpansion (error : Real -> Complex) where
  c1 : Complex
  c2 : Complex
  c3 : Complex
  remainder :
    (fun rho => error rho - firstThreeCorrections c1 c2 c3 rho)
      =O[atTop] beamScale

namespace HalfPowerExpansion

/-- If all three visible correction coefficients vanish, the error is at the
paper's `rho^(-2)` scale. -/
theorem isBigO_beamScale_of_coefficients_eq_zero
    {error : Real -> Complex} (expansion : HalfPowerExpansion error)
    (hc1 : expansion.c1 = 0) (hc2 : expansion.c2 = 0)
    (hc3 : expansion.c3 = 0) :
    error =O[atTop] beamScale := by
  simpa [firstThreeCorrections, hc1, hc2, hc3] using expansion.remainder

end HalfPowerExpansion

/-- Error appearing in the paper-order stationary-phase input. -/
def stationaryPhaseLeadingError
    {V : Type*} [NormedAddCommGroup V] [NormedSpace Real V]
    [MeasurableSpace V]
    (mu : Measure V) (P : PhaseData V) (F : AmplitudeFamily V P.p P.r)
    (rho : Real) : Complex :=
  oscIntegral mu P F rho - F.lead * gaussConst mu P.H

/-! ## Parity-classified stationary-phase coefficients -/

section ParityClassified

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace Real V]
  [FiniteDimensional Real V] [MeasurableSpace V] [BorelSpace V]

/-- A finite half-power expansion whose first and third coefficients are
Gaussian moments of odd jets and whose second coefficient is the moment of an
even jet.  The even coefficient is recorded rather than assumed to vanish. -/
structure ParityClassifiedExpansion
    (mu : Measure V) (H : V →L[Real] V →L[Real] Complex)
    (error : Real -> Complex) extends HalfPowerExpansion error where
  firstJet : V -> Complex
  secondJet : V -> Complex
  thirdJet : V -> Complex
  firstCoefficient : c1 = gaussianMoment mu H firstJet
  secondCoefficient : c2 = gaussianMoment mu H secondJet
  thirdCoefficient : c3 = gaussianMoment mu H thirdJet
  firstJet_odd : forall u, firstJet (-u) = -firstJet u
  secondJet_even : forall u, secondJet (-u) = secondJet u
  thirdJet_odd : forall u, thirdJet (-u) = -thirdJet u

namespace ParityClassifiedExpansion

/-- Odd-jet parity closes the first and third coefficients.  The only
remaining coefficient above the `rho^(-2)` scale is the Gaussian moment of
the even second jet. -/
theorem isBigO_beamScale_of_secondMoment_eq_zero
    (mu : Measure V) [mu.IsAddHaarMeasure]
    (H : V →L[Real] V →L[Real] Complex)
    {error : Real -> Complex}
    (expansion : ParityClassifiedExpansion mu H error)
    (hsecond : gaussianMoment mu H expansion.secondJet = 0) :
    error =O[atTop] beamScale := by
  apply expansion.toHalfPowerExpansion.isBigO_beamScale_of_coefficients_eq_zero
  · rw [expansion.firstCoefficient]
    exact gaussianMoment_eq_zero_of_odd mu H expansion.firstJet
      expansion.firstJet_odd
  · rw [expansion.secondCoefficient]
    exact hsecond
  · rw [expansion.thirdCoefficient]
    exact gaussianMoment_eq_zero_of_odd mu H expansion.thirdJet
      expansion.thirdJet_odd

end ParityClassifiedExpansion

/-! ## Normalized Taylor-jet algebra -/

/-- Taylor coefficients after the factorials and powers generated by the
`rho^(-1/2)` rescaling have been absorbed into the jets. -/
structure NormalizedTaylorJets (V : Type*) [Neg V] where
  amplitude0 : Complex
  amplitude1 : V -> Complex
  amplitude2 : V -> Complex
  phase3 : V -> Complex
  phase4 : V -> Complex
  amplitude1_odd : forall u, amplitude1 (-u) = -amplitude1 u
  amplitude2_even : forall u, amplitude2 (-u) = amplitude2 u
  phase3_odd : forall u, phase3 (-u) = -phase3 u
  phase4_even : forall u, phase4 (-u) = phase4 u

namespace NormalizedTaylorJets

/-- Coefficient integrand at order `rho^(-1/2)` in the normalized expansion
of `a exp(i rho phi)`. -/
def firstCorrectionJet (jets : NormalizedTaylorJets V) (u : V) : Complex :=
  jets.amplitude1 u + Complex.I * jets.amplitude0 * jets.phase3 u

/-- Second-order term in the truncated exponential of the rescaled phase. -/
def phaseSecondCorrectionJet (jets : NormalizedTaylorJets V) (u : V) : Complex :=
  Complex.I * jets.phase4 u - (2 : Complex)⁻¹ * jets.phase3 u ^ 2

/-- Coefficient integrand at order `rho^(-1)`.  Here `phase3` and `phase4`
already include their Taylor factorials. -/
def secondCorrectionJet (jets : NormalizedTaylorJets V) (u : V) : Complex :=
  jets.amplitude2 u +
    Complex.I * jets.amplitude1 u * jets.phase3 u +
    jets.amplitude0 * jets.phaseSecondCorrectionJet u

/-- Amplitude Taylor polynomial through the second rescaled order. -/
def truncatedAmplitudeJet (jets : NormalizedTaylorJets V)
    (u : V) (epsilon : Complex) : Complex :=
  jets.amplitude0 + epsilon * jets.amplitude1 u +
    epsilon ^ 2 * jets.amplitude2 u

/-- Exponential phase Taylor polynomial through the second rescaled order. -/
def truncatedPhaseExponentialJet (jets : NormalizedTaylorJets V)
    (u : V) (epsilon : Complex) : Complex :=
  1 + epsilon * (Complex.I * jets.phase3 u) +
    epsilon ^ 2 * jets.phaseSecondCorrectionJet u

/-- Exact cubic-and-higher remainder left when the two quadratic truncations
are multiplied. -/
def truncatedProductHigherRemainder (jets : NormalizedTaylorJets V)
    (u : V) (epsilon : Complex) : Complex :=
  epsilon ^ 3 *
    (jets.amplitude1 u * jets.phaseSecondCorrectionJet u +
      jets.amplitude2 u * (Complex.I * jets.phase3 u) +
      epsilon * jets.amplitude2 u * jets.phaseSecondCorrectionJet u)

omit [NormedSpace Real V] [FiniteDimensional Real V] [MeasurableSpace V]
  [BorelSpace V] in
/-- Exact algebraic derivation of the first and second correction jets from
the truncated amplitude and phase-exponential product. -/
theorem truncatedProduct_eq_secondOrderExpansion
    (jets : NormalizedTaylorJets V) (u : V) (epsilon : Complex) :
    jets.truncatedAmplitudeJet u epsilon *
        jets.truncatedPhaseExponentialJet u epsilon =
      jets.amplitude0 + epsilon * jets.firstCorrectionJet u +
        epsilon ^ 2 * jets.secondCorrectionJet u +
        jets.truncatedProductHigherRemainder u epsilon := by
  simp only [truncatedAmplitudeJet, truncatedPhaseExponentialJet,
    firstCorrectionJet, secondCorrectionJet,
    truncatedProductHigherRemainder, phaseSecondCorrectionJet]
  ring

omit [NormedSpace Real V] [FiniteDimensional Real V] [MeasurableSpace V]
  [BorelSpace V] in
/-- The first normalized correction is odd. -/
theorem firstCorrectionJet_odd (jets : NormalizedTaylorJets V) (u : V) :
    jets.firstCorrectionJet (-u) = -jets.firstCorrectionJet u := by
  simp only [firstCorrectionJet, jets.amplitude1_odd u, jets.phase3_odd u]
  ring

omit [NormedSpace Real V] [FiniteDimensional Real V] [MeasurableSpace V]
  [BorelSpace V] in
/-- The second normalized correction is even.  Thus its Gaussian moment is
not removed by the parity argument used at the adjacent half-orders. -/
theorem secondCorrectionJet_even (jets : NormalizedTaylorJets V) (u : V) :
    jets.secondCorrectionJet (-u) = jets.secondCorrectionJet u := by
  simp only [secondCorrectionJet, jets.amplitude1_odd u,
    phaseSecondCorrectionJet, jets.amplitude2_even u, jets.phase3_odd u,
    jets.phase4_even u]
  ring

/-- The exact paper-facing second coefficient selected by the normalized
Taylor jets. -/
def secondGaussianCoefficient (mu : Measure V)
    (H : V →L[Real] V →L[Real] Complex)
    (jets : NormalizedTaylorJets V) : Complex :=
  gaussianMoment mu H jets.secondCorrectionJet

omit [FiniteDimensional Real V] [BorelSpace V] in
/-- Cancellation of the normalized even Taylor coefficient is exactly the
Gaussian-moment identity that remains after parity has been used. -/
theorem secondGaussianCoefficient_eq_zero_iff
    (mu : Measure V) (H : V →L[Real] V →L[Real] Complex)
    (jets : NormalizedTaylorJets V) :
    secondGaussianCoefficient mu H jets = 0 ↔
      gaussianMoment mu H jets.secondCorrectionJet = 0 := by
  rfl

end NormalizedTaylorJets

/-- Paper-order bridge from a parity-classified finite expansion.  The
remaining hypothesis is stated as the Gaussian moment of its even second jet,
not as an opaque remainder estimate. -/
theorem paperOrderTwoStationaryPhaseInput_of_parityClassifiedExpansion
    (mu : Measure V) [mu.IsAddHaarMeasure]
    (P : PhaseData V) (F : AmplitudeFamily V P.p P.r)
    (expansion : ParityClassifiedExpansion mu P.H
      (stationaryPhaseLeadingError mu P F))
    (hsecond : gaussianMoment mu P.H expansion.secondJet = 0) :
    PaperOrderTwoStationaryPhaseInput mu P F := by
  simpa [PaperOrderTwoStationaryPhaseInput, stationaryPhaseLeadingError] using
    expansion.isBigO_beamScale_of_secondMoment_eq_zero mu P.H hsecond

end ParityClassified

section ParityGenerated

variable {V : Type*} [NormedAddCommGroup V] [NormedSpace Real V]
  [FiniteDimensional Real V] [MeasurableSpace V] [BorelSpace V]

/-- A half-power expansion whose odd coefficients are generated by linear and
cubic jets. The second, even coefficient remains explicit. -/
structure ParityGeneratedExpansion
    (mu : Measure V) (H : V →L[Real] V →L[Real] Complex)
    (ell : V →L[Real] Complex)
    (cubic : V →L[Real] V →L[Real] V →L[Real] Complex)
    (error : Real -> Complex) extends HalfPowerExpansion error where
  firstCoefficient : c1 = linearGaussianCoefficient mu H ell
  thirdCoefficient : c3 = cubicGaussianCoefficient mu H cubic

namespace ParityGeneratedExpansion

/-- Parity discharges the odd corrections, so the `rho^(-2)` conclusion is
equivalent here to supplying the even second-coefficient cancellation. -/
theorem isBigO_beamScale_of_secondCoefficient_eq_zero
    (mu : Measure V) [mu.IsAddHaarMeasure]
    (H : V →L[Real] V →L[Real] Complex)
    (ell : V →L[Real] Complex)
    (cubic : V →L[Real] V →L[Real] V →L[Real] Complex)
    {error : Real -> Complex}
    (expansion : ParityGeneratedExpansion mu H ell cubic error)
    (hc2 : expansion.c2 = 0) :
    error =O[atTop] beamScale := by
  apply expansion.toHalfPowerExpansion.isBigO_beamScale_of_coefficients_eq_zero
  · rw [expansion.firstCoefficient]
    exact linearGaussianCoefficient_eq_zero mu H ell
  · exact hc2
  · rw [expansion.thirdCoefficient]
    exact cubicGaussianCoefficient_eq_zero mu H cubic

end ParityGeneratedExpansion

/-- Paper-order bridge from a source-specific finite expansion. Odd
coefficients are discharged by Gaussian parity; the even coefficient remains
the one explicit hypothesis. -/
theorem paperOrderTwoStationaryPhaseInput_of_parityGeneratedExpansion
    (mu : Measure V) [mu.IsAddHaarMeasure]
    (P : PhaseData V) (F : AmplitudeFamily V P.p P.r)
    (ell : V →L[Real] Complex)
    (cubic : V →L[Real] V →L[Real] V →L[Real] Complex)
    (expansion : ParityGeneratedExpansion mu P.H ell cubic
      (stationaryPhaseLeadingError mu P F))
    (hsecond : expansion.c2 = 0) :
    PaperOrderTwoStationaryPhaseInput mu P F := by
  simpa [PaperOrderTwoStationaryPhaseInput, stationaryPhaseLeadingError] using
    expansion.isBigO_beamScale_of_secondCoefficient_eq_zero
      mu P.H ell cubic hsecond

end ParityGenerated

end LiuWang2025SemilinearWaveComplexStationaryPhase
