import LiuWang.LiuWang2025SemilinearWaveGaussianLocalization
import LiuWang.LiuWang2025SemilinearWaveReflectedBeamBoundaryDecay

/-!
# Liu--Wang 2025: quantitative equation-(4.4) recovery packet

Equation (4.4) in Liu--Wang has a localized principal term and an
`O(rho^-2)` error.  This module verifies the quantitative closure that was
previously left as an abstract `error -> 0` input:

* the exact integer-frequency rate `rho^-2` tends to zero;
* any complex error bounded by a nonnegative constant times that rate tends
  to zero;
* combining this generated remainder limit with the checked normalized
  Gaussian localization and the checked reflected-boundary rate yields
  pointwise recovery of the selected Taylor coefficient.

The estimate producing the `O(rho^-2)` bound, the Lorentzian phase/Hessian
normal-form reduction, and the reflected-beam boundary estimate remain
source-specific analytic inputs.  Their consequences are no longer separate
limit hypotheses.
-/

noncomputable section

open Filter MeasureTheory Topology
open scoped RealInnerProductSpace

namespace LiuWang2025SemilinearWaveEquation44QuantitativeRecovery

open LiuWang2025SemilinearWaveGaussianLocalization
open LiuWang2025SemilinearWaveReflectedBeamBoundaryDecay

/-- The explicit `rho^-2` remainder rate in equation (4.4).  Its value at
`rho = 0` is immaterial for the high-frequency limit. -/
def equation44RemainderRate (rho : Nat) : Real :=
  (rho : Real) ^ (-(2 : Real))

theorem equation44RemainderRate_tendsto_zero :
    Tendsto equation44RemainderRate atTop (nhds 0) := by
  exact (tendsto_rpow_neg_atTop (by norm_num : (0 : Real) < 2)).comp
    tendsto_natCast_atTop_atTop

/-- A quantitative `O(rho^-2)` norm bound generates the error limit used in
the coefficient-recovery closure. -/
theorem error_tendsto_zero_of_equation44_rate
    {E : Type*} [SeminormedAddCommGroup E]
    (error : Nat -> E) (boundConstant : Real)
    (hbound : ∀ᶠ rho in atTop,
      ‖error rho‖ <= boundConstant * equation44RemainderRate rho) :
    Tendsto error atTop (nhds 0) := by
  rw [tendsto_zero_iff_norm_tendsto_zero]
  apply squeeze_zero' (Eventually.of_forall fun rho => norm_nonneg (error rho)) hbound
  simpa using
    tendsto_const_nhds.mul equation44RemainderRate_tendsto_zero

variable {V : Type*} [NormedAddCommGroup V] [InnerProductSpace Real V]
  [MeasurableSpace V] [BorelSpace V] [FiniteDimensional Real V]

/-- Source-facing equation-(4.4) packet in which both asymptotic error limits
are generated from quantitative estimates. -/
structure QuantitativeEquation44RecoveryData where
  point : V
  coefficient : V -> Complex
  amplitude0 : V -> Complex
  amplitude1 : V -> Complex
  amplitude2 : V -> Complex
  amplitude3 : V -> Complex
  stationaryConstant : Complex
  stationaryConstant_ne_zero : stationaryConstant ≠ 0
  amplitudeProduct_ne_zero :
    amplitudeProductAt amplitude0 amplitude1 amplitude2 amplitude3 point ≠ 0
  interactionProfile_integrable : Integrable
    (cubicInteractionProfile coefficient
      amplitude0 amplitude1 amplitude2 amplitude3)
  interactionProfile_continuousAt : ContinuousAt
    (cubicInteractionProfile coefficient
      amplitude0 amplitude1 amplitude2 amplitude3) point
  error : Nat -> Complex
  errorBoundConstant : Real
  errorBoundConstant_nonneg : 0 <= errorBoundConstant
  error_rate : ∀ᶠ rho in atTop,
    ‖error rho‖ <= errorBoundConstant * equation44RemainderRate rho
  boundaryPacket : BoundaryDecayPacket Complex
  integralIdentity : forall rho,
    scaledGaussianPrincipal stationaryConstant coefficient
        amplitude0 amplitude1 amplitude2 amplitude3 point rho +
      error rho = boundaryPacket.boundaryTrace rho

namespace QuantitativeEquation44RecoveryData

/-- The paper's `O(rho^-2)` estimate supplies the analytic error limit. -/
theorem error_tendsto_zero
    (data : QuantitativeEquation44RecoveryData (V := V)) :
    Tendsto data.error atTop (nhds 0) :=
  error_tendsto_zero_of_equation44_rate
    data.error data.errorBoundConstant data.error_rate

/-- The registered reflected-beam exponent supplies the inaccessible-boundary
limit. -/
theorem boundary_tendsto_zero
    (data : QuantitativeEquation44RecoveryData (V := V)) :
    Tendsto data.boundaryPacket.boundaryTrace atTop (nhds 0) :=
  data.boundaryPacket.boundaryTrace_tendsto_zero

/-- Forgetful map to the Gaussian recovery packet.  Its principal, remainder,
and boundary limits are all generated by checked theorems. -/
def toGaussianPointRecoveryData
    (data : QuantitativeEquation44RecoveryData (V := V)) :
    GaussianPointRecoveryData (V := V) where
  point := data.point
  coefficient := data.coefficient
  amplitude0 := data.amplitude0
  amplitude1 := data.amplitude1
  amplitude2 := data.amplitude2
  amplitude3 := data.amplitude3
  stationaryConstant := data.stationaryConstant
  stationaryConstant_ne_zero := data.stationaryConstant_ne_zero
  amplitudeProduct_ne_zero := data.amplitudeProduct_ne_zero
  interactionProfile_integrable := data.interactionProfile_integrable
  interactionProfile_continuousAt := data.interactionProfile_continuousAt
  error := data.error
  boundary := data.boundaryPacket.boundaryTrace
  error_tendsto_zero := data.error_tendsto_zero
  inaccessibleBoundary_tendsto_zero := data.boundary_tendsto_zero
  integralIdentity := data.integralIdentity

/-- Quantitative equation-(4.4) point-recovery endpoint. -/
theorem coefficient_at_point_eq_zero
    (data : QuantitativeEquation44RecoveryData (V := V)) :
    data.coefficient data.point = 0 :=
  data.toGaussianPointRecoveryData.coefficient_at_point_eq_zero

/-- Product-facing certificate: both explicit rates vanish, the normalized
Gaussian principal localizes, and the selected coefficient is zero. -/
structure Certificate
    (data : QuantitativeEquation44RecoveryData (V := V)) : Prop where
  remainderRateVanishes :
    Tendsto equation44RemainderRate atTop (nhds 0)
  remainderBoundConstantNonnegative : 0 <= data.errorBoundConstant
  remainderRateBound : ∀ᶠ rho in atTop,
    ‖data.error rho‖ <=
      data.errorBoundConstant * equation44RemainderRate rho
  remainderVanishes : Tendsto data.error atTop (nhds 0)
  boundaryExponentPositive :
    0 < boundaryDecayExponent data.boundaryPacket.order
      data.boundaryPacket.derivativeOrder
  inaccessibleBoundaryVanishes :
    Tendsto data.boundaryPacket.boundaryTrace atTop (nhds 0)
  principalLimit : Tendsto
    (scaledGaussianPrincipal data.stationaryConstant data.coefficient
      data.amplitude0 data.amplitude1 data.amplitude2 data.amplitude3
      data.point)
    atTop
    (nhds
      (data.stationaryConstant * data.coefficient data.point *
        amplitudeProductAt data.amplitude0 data.amplitude1 data.amplitude2
          data.amplitude3 data.point))
  coefficientZero : data.coefficient data.point = 0

def certificate (data : QuantitativeEquation44RecoveryData (V := V)) :
    Certificate data where
  remainderRateVanishes := equation44RemainderRate_tendsto_zero
  remainderBoundConstantNonnegative := data.errorBoundConstant_nonneg
  remainderRateBound := data.error_rate
  remainderVanishes := data.error_tendsto_zero
  boundaryExponentPositive := data.boundaryPacket.exponent_pos
  inaccessibleBoundaryVanishes := data.boundary_tendsto_zero
  principalLimit := data.toGaussianPointRecoveryData.certificate.principalLimit
  coefficientZero := data.coefficient_at_point_eq_zero

end QuantitativeEquation44RecoveryData

end LiuWang2025SemilinearWaveEquation44QuantitativeRecovery
