import LiuWang.LiuWang2025SemilinearWaveGeneratedPartialDNMap

/-!
# Liu--Wang product-boundary partial DN realization

The partial-data Green argument splits the lateral boundary into the
accessible set and its complement.  The abstract generated partial-DN module
allows arbitrary restriction maps and assumes their pairing-partition law.
This file realizes that algebra on an explicit product boundary-flux carrier.

The full normal trace takes values in
`AccessibleFlux x InaccessibleFlux`.  The accessible and inaccessible
restrictions are the canonical continuous projections, and the full boundary
pairing is defined as the sum of the two component pairings.  Consequently the
partition identity and the identification of the accessible measured trace
are generated by construction.  Equality of the nonlinear accessible
partial-DN maps then differentiates to the third trace and yields equation
(4.3) through the existing directed Green theorem.

The remaining source-facing work is the concrete Lorentzian Sobolev trace
theorem, identification of this product carrier with restriction to `Gamma`
and `Sigma \ Gamma`, and the geometric/PDE realization of the supplied Green
formula.
-/

noncomputable section

open Filter Topology

namespace LiuWang2025SemilinearWaveProductBoundaryPartialDN

open LiuWang2025SemilinearWaveThirdOrderGreen
open LiuWang2025SemilinearWaveGeneratedThirdOrder
open LiuWang2025SemilinearWaveDirectedGreenRealization
open LiuWang2025SemilinearWaveGeneratedPartialDNMap

variable {Parameter State Residual Probe BackwardResidual : Type*}
variable {BoundaryValue AccessibleFlux InaccessibleFlux : Type*}

variable [NormedAddCommGroup Parameter] [NormedSpace Complex Parameter]
variable [CompleteSpace Parameter]
variable [NormedAddCommGroup State] [NormedSpace Complex State]
variable [CompleteSpace State]
variable [NormedAddCommGroup Residual] [NormedSpace Complex Residual]
variable [CompleteSpace Residual]
variable [AddCommGroup Probe] [Module Complex Probe]
variable [AddCommGroup BackwardResidual] [Module Complex BackwardResidual]
variable [AddCommGroup BoundaryValue] [Module Complex BoundaryValue]
variable [NormedAddCommGroup AccessibleFlux]
variable [NormedSpace Complex AccessibleFlux]
variable [CompleteSpace AccessibleFlux]
variable [NormedAddCommGroup InaccessibleFlux]
variable [NormedSpace Complex InaccessibleFlux]

/-- Directed wave Green data whose full normal trace is an explicit pair of
accessible and inaccessible fluxes.  The full boundary pairing is generated
below, so neither it nor its partition law is a field. -/
structure ProductBoundaryGreenData where
  forwardTimeSecond : State →ₗ[Complex] Residual
  forwardSpatial : State →ₗ[Complex] Residual
  forwardWave : State →ₗ[Complex] Residual
  backwardTimeSecond : Probe →ₗ[Complex] BackwardResidual
  backwardSpatial : Probe →ₗ[Complex] BackwardResidual
  backwardWave : Probe →ₗ[Complex] BackwardResidual
  bulkPairing : Residual →ₗ[Complex] Probe →ₗ[Complex] Complex
  adjointBulkPairing : State →ₗ[Complex] BackwardResidual →ₗ[Complex] Complex
  continuousNormalTrace : State →L[Complex]
    (AccessibleFlux × InaccessibleFlux)
  probeTrace : Probe →ₗ[Complex] BoundaryValue
  accessiblePairing :
    AccessibleFlux →ₗ[Complex] BoundaryValue →ₗ[Complex] Complex
  inaccessiblePairing :
    InaccessibleFlux →ₗ[Complex] BoundaryValue →ₗ[Complex] Complex
  forwardWave_decomposition :
    forwardWave = forwardTimeSecond - forwardSpatial
  backwardWave_decomposition :
    backwardWave = backwardTimeSecond - backwardSpatial
  timeIntegrationByParts : forall (u : State) (v : Probe),
    bulkPairing (forwardTimeSecond u) v =
      adjointBulkPairing u (backwardTimeSecond v)
  spatialGreenFormula : forall (u : State) (v : Probe),
    bulkPairing (forwardSpatial u) v -
        adjointBulkPairing u (backwardSpatial v) =
      accessiblePairing (continuousNormalTrace u).1 (probeTrace v) +
        inaccessiblePairing (continuousNormalTrace u).2 (probeTrace v)

namespace ProductBoundaryGreenData

/-- The full boundary pairing on the explicit product carrier. -/
def fullBoundaryPairing
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux)) :
    (AccessibleFlux × InaccessibleFlux) →ₗ[Complex]
      BoundaryValue →ₗ[Complex] Complex where
  toFun flux := D.accessiblePairing flux.1 + D.inaccessiblePairing flux.2
  map_add' x y := by
    ext trace
    simp
    abel
  map_smul' scalar x := by
    ext trace
    simp

@[simp] theorem fullBoundaryPairing_apply
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux))
    (flux : AccessibleFlux × InaccessibleFlux) (trace : BoundaryValue) :
    D.fullBoundaryPairing flux trace =
      D.accessiblePairing flux.1 trace +
        D.inaccessiblePairing flux.2 trace := rfl

/-- Build the source-ordered directed Green model.  Its spatial Green formula
is exactly the supplied componentwise identity. -/
def toDirectedWaveGreenModel
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux)) :
    DirectedWaveGreenModel
      (ForwardGraph := State) (BackwardGraph := Probe)
      (ForwardResidual := Residual) (BackwardResidual := BackwardResidual)
      (BoundaryFlux := AccessibleFlux × InaccessibleFlux)
      (BoundaryValue := BoundaryValue) where
  forwardTimeSecond := D.forwardTimeSecond
  forwardSpatial := D.forwardSpatial
  forwardWave := D.forwardWave
  backwardTimeSecond := D.backwardTimeSecond
  backwardSpatial := D.backwardSpatial
  backwardWave := D.backwardWave
  bulkPairing := D.bulkPairing
  adjointBulkPairing := D.adjointBulkPairing
  normalTrace := D.continuousNormalTrace.toLinearMap
  probeTrace := D.probeTrace
  fullBoundaryPairing := D.fullBoundaryPairing
  forwardWave_decomposition := D.forwardWave_decomposition
  backwardWave_decomposition := D.backwardWave_decomposition
  timeIntegrationByParts := D.timeIntegrationByParts
  spatialGreenFormula := by
    intro u v
    simpa using D.spatialGreenFormula u v

@[simp] theorem toDirectedWaveGreenModel_normalTrace
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux))
    (u : State) :
    D.toDirectedWaveGreenModel.normalTrace u = D.continuousNormalTrace u := rfl

variable {order : Nat}
variable
  {D : ProductBoundaryGreenData
    (State := State) (Residual := Residual) (Probe := Probe)
    (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
    (AccessibleFlux := AccessibleFlux)
    (InaccessibleFlux := InaccessibleFlux)}
variable
  {comparison : GeneratedCubicComparisonData
    (Parameter := Parameter)
    D.toDirectedWaveGreenModel.toWaveGreenIdentityEngine order}

/-- Canonical generated partial-DN realization.  Both boundary restrictions,
their partition identity, and the accessible trace identification are now
definitions rather than supplied proof fields. -/
def toGeneratedPartialDNRealization
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux))
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter)
      D.toDirectedWaveGreenModel.toWaveGreenIdentityEngine order) :
    GeneratedPartialDNRealization
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux)
      comparison where
  accessibleRestriction :=
    ContinuousLinearMap.fst Complex AccessibleFlux InaccessibleFlux
  inaccessibleRestriction :=
    ContinuousLinearMap.snd Complex AccessibleFlux InaccessibleFlux
  accessiblePairing := D.accessiblePairing
  inaccessiblePairing := D.inaccessiblePairing
  boundaryPairing_partition := by
    intro flux trace
    rfl
  accessibleNormalTrace :=
    (ContinuousLinearMap.fst Complex AccessibleFlux InaccessibleFlux).comp
      D.continuousNormalTrace
  accessibleNormalTrace_eq := by
    intro state
    rfl

/-- The generated accessible nonlinear measurement maps, now based on the
canonical first projection of the product normal trace. -/
def EventuallyEqualGeneratedPartialDNMaps
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux))
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter)
      D.toDirectedWaveGreenModel.toWaveGreenIdentityEngine order)
    (horder : 3 <= order) : Prop :=
  (D.toGeneratedPartialDNRealization comparison)
    |>.EventuallyEqualGeneratedPartialDNMaps horder

/-- Equality of the nonlinear accessible partial-DN maps yields equality of
the accessible third traces in the explicit product-boundary model. -/
theorem generatedThirdAccessibleNormalTrace_eq
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux))
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter)
      D.toDirectedWaveGreenModel.toWaveGreenIdentityEngine order)
    (horder : 3 <= order)
    (hdata : D.EventuallyEqualGeneratedPartialDNMaps comparison horder)
    (direction : Fin 3 -> Parameter) :
    (D.continuousNormalTrace (comparison.thirdVariation1 horder direction)).1 =
      (D.continuousNormalTrace
        (comparison.thirdVariation2 horder direction)).1 := by
  exact (D.toGeneratedPartialDNRealization comparison)
    |>.generatedThirdAccessibleNormalTrace_eq horder hdata direction

/-- End-to-end equation (4.3) in the explicit product-boundary realization. -/
theorem equation43_sourcePairing_eq_inaccessibleBoundary
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux))
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter)
      D.toDirectedWaveGreenModel.toWaveGreenIdentityEngine order)
    (horder : 3 <= order)
    (hdata : D.EventuallyEqualGeneratedPartialDNMaps comparison horder)
    (direction : Fin 3 -> Parameter) (probe : Probe)
    (hprobe : D.backwardWave probe = 0) :
    D.bulkPairing
        (comparison.toThirdOrderWaveDifferenceData horder direction).coefficientDifferenceSource
        probe =
      D.inaccessiblePairing
        (D.continuousNormalTrace
          (comparison.toThirdOrderWaveDifferenceData horder direction).variationDifference).2
        (D.probeTrace probe) := by
  exact (D.toGeneratedPartialDNRealization comparison)
    |>.equation43_sourcePairing_eq_inaccessibleBoundary_of_generatedPartialDN
      horder hdata direction probe hprobe

/-- Product-native certificate for the canonical boundary partition, third
accessible trace equality, and equation (4.3). -/
structure Certificate
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux))
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter)
      D.toDirectedWaveGreenModel.toWaveGreenIdentityEngine order)
    (horder : 3 <= order)
    (hdata : D.EventuallyEqualGeneratedPartialDNMaps comparison horder)
    (direction : Fin 3 -> Parameter) : Prop where
  boundaryPartition : forall flux trace,
    D.fullBoundaryPairing flux trace =
      D.accessiblePairing flux.1 trace +
        D.inaccessiblePairing flux.2 trace
  accessibleThirdTracesAgree :
    (D.continuousNormalTrace (comparison.thirdVariation1 horder direction)).1 =
      (D.continuousNormalTrace
        (comparison.thirdVariation2 horder direction)).1
  equation43 : forall probe, D.backwardWave probe = 0 ->
    D.bulkPairing
        (comparison.toThirdOrderWaveDifferenceData horder direction).coefficientDifferenceSource
        probe =
      D.inaccessiblePairing
        (D.continuousNormalTrace
          (comparison.toThirdOrderWaveDifferenceData horder direction).variationDifference).2
        (D.probeTrace probe)

def certificate
    (D : ProductBoundaryGreenData
      (State := State) (Residual := Residual) (Probe := Probe)
      (BackwardResidual := BackwardResidual) (BoundaryValue := BoundaryValue)
      (AccessibleFlux := AccessibleFlux)
      (InaccessibleFlux := InaccessibleFlux))
    (comparison : GeneratedCubicComparisonData
      (Parameter := Parameter)
      D.toDirectedWaveGreenModel.toWaveGreenIdentityEngine order)
    (horder : 3 <= order)
    (hdata : D.EventuallyEqualGeneratedPartialDNMaps comparison horder)
    (direction : Fin 3 -> Parameter) :
    Certificate D comparison horder hdata direction where
  boundaryPartition := D.fullBoundaryPairing_apply
  accessibleThirdTracesAgree :=
    D.generatedThirdAccessibleNormalTrace_eq comparison horder hdata direction
  equation43 :=
    D.equation43_sourcePairing_eq_inaccessibleBoundary
      comparison horder hdata direction

end ProductBoundaryGreenData

end LiuWang2025SemilinearWaveProductBoundaryPartialDN
