import LiuWang.LiuWang2025SemilinearWaveLinearization
import LiuWang.LiuWang2025SemilinearWaveThirdOrderGreen
import Mathlib.Analysis.Complex.Basic
import Mathlib.Topology.Algebra.InfiniteSum.Basic

/-!
# Liu--Wang partial-data Gaussian-beam recovery closure

The partial-data identity in Liu--Wang contains an inaccessible-boundary
term.  Reflected Gaussian beams are constructed so that their boundary norm
vanishes as the frequency grows.  This module verifies two closure steps:

* a Cauchy--Schwarz-type norm bound transfers beam decay to decay of the
  inaccessible-boundary pairing;
* stationary-phase convergence, vanishing remainder, and vanishing boundary
  leakage force the recovered Taylor coefficient to vanish at the selected
  reachable point whenever the stationary-phase constant and amplitude
  product are nonzero.

The construction of the reflected beams, their remainder estimate, and the
stationary-phase expansion remain source-specific analytic inputs.  Their
role and exact output are visible in the theorem statements.
-/

noncomputable section

open Filter Topology

namespace LiuWang2025SemilinearWaveGaussianRecovery

open LiuWang2025SemilinearWaveThirdOrderGreen

/-- Abstract Cauchy--Schwarz closure for the inaccessible-boundary term. -/
theorem boundaryPairing_tendsto_zero_of_norm_bound
    {E : Type*} [SeminormedAddCommGroup E]
    (pairing : Nat -> E) (beamBoundaryNorm : Nat -> Real)
    (fluxNorm : Real)
    (hbound : forall rho,
      ‖pairing rho‖ ≤ fluxNorm * beamBoundaryNorm rho)
    (hbeam : Tendsto beamBoundaryNorm atTop (nhds 0)) :
    Tendsto pairing atTop (nhds 0) := by
  rw [tendsto_zero_iff_norm_tendsto_zero]
  apply squeeze_zero (fun rho => norm_nonneg (pairing rho)) hbound
  simpa using (tendsto_const_nhds.mul hbeam)

/-- If the principal stationary-phase term converges to
`constant * coefficient * amplitudeProduct`, while both the analytic error
and inaccessible-boundary term vanish, then the coefficient is zero. -/
theorem coefficient_eq_zero_of_stationary_phase_and_boundary_decay
    (coefficient stationaryConstant amplitudeProduct : Complex)
    (hconstant : stationaryConstant ≠ 0)
    (hamplitude : amplitudeProduct ≠ 0)
    (principal error boundary : Nat -> Complex)
    (hprincipal : Tendsto principal atTop
      (nhds (stationaryConstant * coefficient * amplitudeProduct)))
    (herror : Tendsto error atTop (nhds 0))
    (hboundary : Tendsto boundary atTop (nhds 0))
    (hidentity : forall rho,
      principal rho + error rho = boundary rho) :
    coefficient = 0 := by
  have hleft : Tendsto (fun rho => principal rho + error rho) atTop
      (nhds (stationaryConstant * coefficient * amplitudeProduct)) := by
    simpa using hprincipal.add herror
  have hleftZero : Tendsto (fun rho => principal rho + error rho) atTop
      (nhds 0) := by
    simpa only [hidentity] using hboundary
  have hproduct : stationaryConstant * coefficient * amplitudeProduct = 0 :=
    tendsto_nhds_unique hleft hleftZero
  rcases mul_eq_zero.mp hproduct with hconstantCoefficient | hAmplitudeZero
  · exact (mul_eq_zero.mp hconstantCoefficient).resolve_left hconstant
  · exact (hamplitude hAmplitudeZero).elim

/-- All asymptotic inputs needed to recover one coefficient at one point of
the causal interaction region. -/
structure PointRecoveryData where
  coefficient : Complex
  stationaryConstant : Complex
  amplitudeProduct : Complex
  principal : Nat -> Complex
  error : Nat -> Complex
  boundary : Nat -> Complex
  stationaryConstant_ne_zero : stationaryConstant ≠ 0
  amplitudeProduct_ne_zero : amplitudeProduct ≠ 0
  principal_tendsto : Tendsto principal atTop
    (nhds (stationaryConstant * coefficient * amplitudeProduct))
  error_tendsto_zero : Tendsto error atTop (nhds 0)
  inaccessibleBoundary_tendsto_zero : Tendsto boundary atTop (nhds 0)
  integralIdentity : forall rho, principal rho + error rho = boundary rho

namespace PointRecoveryData

/-- Pointwise recovery endpoint generated by the asymptotic packet. -/
theorem coefficient_eq_zero (data : PointRecoveryData) :
    data.coefficient = 0 :=
  coefficient_eq_zero_of_stationary_phase_and_boundary_decay
    data.coefficient data.stationaryConstant data.amplitudeProduct
    data.stationaryConstant_ne_zero data.amplitudeProduct_ne_zero
    data.principal data.error data.boundary
    data.principal_tendsto data.error_tendsto_zero
    data.inaccessibleBoundary_tendsto_zero data.integralIdentity

/-- One-object certificate for a recovered point in the reachable region. -/
structure Certificate (data : PointRecoveryData) : Prop where
  principalLimit : Tendsto data.principal atTop
    (nhds (data.stationaryConstant * data.coefficient * data.amplitudeProduct))
  boundaryLimit : Tendsto data.boundary atTop (nhds 0)
  coefficientZero : data.coefficient = 0

def certificate (data : PointRecoveryData) : Certificate data where
  principalLimit := data.principal_tendsto
  boundaryLimit := data.inaccessibleBoundary_tendsto_zero
  coefficientZero := data.coefficient_eq_zero

end PointRecoveryData

/-! ## Source equation and partial Green identity to beam recovery -/

section PartialGreenBridge

variable {Coefficient FirstVariation State Residual Probe : Type*}
variable {BoundaryFlux BoundaryValue : Type*}
variable [AddCommGroup Coefficient] [Module Complex Coefficient]
variable [AddCommGroup FirstVariation] [Module Complex FirstVariation]
variable [AddCommGroup State] [Module Complex State]
variable [AddCommGroup Residual] [Module Complex Residual]
variable [AddCommGroup Probe] [Module Complex Probe]
variable [AddCommGroup BoundaryFlux] [Module Complex BoundaryFlux]
variable [AddCommGroup BoundaryValue] [Module Complex BoundaryValue]

variable
  {G : WaveGreenIdentityEngine
    (State := State) (Residual := Residual) (Probe := Probe)
    (BoundaryFlux := BoundaryFlux) (BoundaryValue := BoundaryValue)}
  {D : ThirdOrderWaveDifferenceData G
    (Coefficient := Coefficient) (FirstVariation := FirstVariation)}

/-- The inaccessible-boundary sequence generated by a frequency-indexed
family of partial Green packets. -/
def inaccessibleBoundarySequence
    (packets : Nat -> PartialDataGreenPacket G D) : Nat -> Complex :=
  fun rho =>
    (packets rho).inaccessibleBoundaryPairing
      (G.normalTrace D.variationDifference)
      (G.probeTrace (packets rho).probe)

/-- A decomposition of the cubic bulk pairing into principal and error terms,
together with the checked partial Green identity, produces exactly the
identity consumed by the stationary-phase closure. -/
theorem partialGreen_integralIdentity
    (packets : Nat -> PartialDataGreenPacket G D)
    (principal error : Nat -> Complex)
    (hdecomposition : forall rho,
      principal rho + error rho =
        G.bulkPairing D.coefficientDifferenceSource (packets rho).probe) :
    forall rho,
      principal rho + error rho = inaccessibleBoundarySequence packets rho := by
  intro rho
  rw [hdecomposition rho]
  exact (packets rho).cubicSourcePairing_eq_inaccessibleBoundary

/-- End-to-end point recovery from the checked third-order difference
equation, checked partial-boundary bookkeeping, beam asymptotics, and boundary
decay.  The reflected-beam construction itself remains an explicit input via
the packet family and limit hypotheses. -/
theorem coefficient_eq_zero_of_partialGreen_beam_packets
    (coefficient stationaryConstant amplitudeProduct : Complex)
    (hconstant : stationaryConstant ≠ 0)
    (hamplitude : amplitudeProduct ≠ 0)
    (packets : Nat -> PartialDataGreenPacket G D)
    (principal error : Nat -> Complex)
    (hdecomposition : forall rho,
      principal rho + error rho =
        G.bulkPairing D.coefficientDifferenceSource (packets rho).probe)
    (hprincipal : Tendsto principal atTop
      (nhds (stationaryConstant * coefficient * amplitudeProduct)))
    (herror : Tendsto error atTop (nhds 0))
    (hboundary : Tendsto (inaccessibleBoundarySequence packets) atTop (nhds 0)) :
    coefficient = 0 := by
  exact coefficient_eq_zero_of_stationary_phase_and_boundary_decay
    coefficient stationaryConstant amplitudeProduct hconstant hamplitude
    principal error (inaccessibleBoundarySequence packets)
    hprincipal herror hboundary
    (partialGreen_integralIdentity packets principal error hdecomposition)

end PartialGreenBridge

/-- Pointwise packets over every point of the paper's causally reachable set
produce recovery on that set and nowhere larger. -/
theorem coefficient_zero_on_reachable_set
    {Point : Type*} (reachable : Set Point)
    (data : forall p : Point, p ∈ reachable -> PointRecoveryData) :
    forall (p : Point) (hp : p ∈ reachable),
      (data p hp).coefficient = 0 := by
  intro p hp
  exact (data p hp).coefficient_eq_zero

end LiuWang2025SemilinearWaveGaussianRecovery
