import LiuWang.LiuWang2025SemilinearWaveGaussianLocalization

/-!
# Liu--Wang 2025: four-beam phase balance at the interaction point

In the proof of cubic recovery in Liu--Wang, four light-like covectors and
real weights are chosen at the interaction point so that

`kappa_0 theta_0 + kappa_1 theta_1 + kappa_2 theta_2 + kappa_3 theta_3 = 0`.

The combined Gaussian-beam phase is
`S = sum_j kappa_j phi_j`.  This module checks the source transition from the
individual phase jets `d phi_j = theta_j` to Lemma 4.1(i)--(ii):
`S(p)=0` and `dS(p)=0`.  The geometric existence of the four null covectors,
their weights, and their compatible beam phases remains a source-facing
input; the critical-point calculation is not.
-/

noncomputable section

open scoped BigOperators

namespace LiuWang2025SemilinearWavePhaseBalance

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace Real X]

/-- The source's four-beam combined complex phase. -/
def weightedPhase
    (weight : Fin 4 -> Real) (phase : Fin 4 -> X -> Complex) :
    X -> Complex :=
  fun x => ∑ j, weight j • phase j x

/-- Weighted sum of the four phase covectors at the interaction point. -/
def weightedCovector
    (weight : Fin 4 -> Real)
    (covector : Fin 4 -> X →L[Real] Complex) : X →L[Real] Complex :=
  ∑ j, weight j • covector j

/-- Differentiation commutes with the exact four-term weighted phase sum. -/
theorem hasFDerivAt_weightedPhase
    (weight : Fin 4 -> Real) (phase : Fin 4 -> X -> Complex)
    (covector : Fin 4 -> X →L[Real] Complex) (point : X)
    (hphase : forall j, HasFDerivAt (phase j) (covector j) point) :
    HasFDerivAt (weightedPhase weight phase)
      (weightedCovector weight covector) point := by
  unfold weightedPhase weightedCovector
  exact HasFDerivAt.fun_sum fun j _ => (hphase j).const_smul (weight j)

/-- Source-facing four-beam jet packet at the selected interaction point.
Only geometric data are registered: the four phase values and differentials,
and the null-covector balance. -/
structure FourBeamPhaseBalanceData (X : Type*)
    [NormedAddCommGroup X] [NormedSpace Real X] where
  point : X
  phase : Fin 4 -> X -> Complex
  weight : Fin 4 -> Real
  covector : Fin 4 -> X →L[Real] Complex
  phase_zero : forall j, phase j point = 0
  phase_hasFDerivAt : forall j,
    HasFDerivAt (phase j) (covector j) point
  weightedCovectorBalance : weightedCovector weight covector = 0

namespace FourBeamPhaseBalanceData

/-- Lemma 4.1(i): the combined phase vanishes at the interaction point. -/
theorem weightedPhase_at_eq_zero (data : FourBeamPhaseBalanceData X) :
    weightedPhase data.weight data.phase data.point = 0 := by
  simp [weightedPhase, data.phase_zero]

/-- Lemma 4.1(ii), in Frechet form: null-covector balance gives the combined
phase the zero differential at the interaction point. -/
theorem weightedPhase_hasFDerivAt_zero
    (data : FourBeamPhaseBalanceData X) :
    HasFDerivAt (weightedPhase data.weight data.phase)
      (0 : X →L[Real] Complex) data.point := by
  simpa [data.weightedCovectorBalance] using
    hasFDerivAt_weightedPhase data.weight data.phase data.covector data.point
      data.phase_hasFDerivAt

/-- The computed Frechet derivative of the combined phase is exactly zero. -/
theorem fderiv_weightedPhase_eq_zero
    (data : FourBeamPhaseBalanceData X) :
    fderiv Real (weightedPhase data.weight data.phase) data.point = 0 :=
  data.weightedPhase_hasFDerivAt_zero.fderiv

/-- Auditable certificate for the two source conclusions generated by the
four null-covector balance. -/
structure Certificate (data : FourBeamPhaseBalanceData X) : Prop where
  phaseValueZero : weightedPhase data.weight data.phase data.point = 0
  phaseHasZeroDifferential :
    HasFDerivAt (weightedPhase data.weight data.phase)
      (0 : X →L[Real] Complex) data.point
  phaseDifferentialZero :
    fderiv Real (weightedPhase data.weight data.phase) data.point = 0

def certificate (data : FourBeamPhaseBalanceData X) : Certificate data where
  phaseValueZero := data.weightedPhase_at_eq_zero
  phaseHasZeroDifferential := data.weightedPhase_hasFDerivAt_zero
  phaseDifferentialZero := data.fderiv_weightedPhase_eq_zero

end FourBeamPhaseBalanceData

end LiuWang2025SemilinearWavePhaseBalance
